### PR TITLE
New RawIO: AxographRawIO

### PR DESCRIPTION
**Pull request by jpgill86**
The `AxographIO` class was introduced in Neo 0.7.0 (#550; thanks @will-hart for your hard work on that!). It depends on an external library, [axographio](https://github.com/CWRUChielLab/axographio), for which I am currently the code maintainer.

I've implemented a RawIO class for AxoGraph files that eliminates the need for the dependency and provides the first (I think) pure-Python solution for reading AxoGraph files (the axographio package uses compiled C++ code distributed by AxoGraph's developer). The new RawIO class also allows much faster access to large files (they don't need to be entirely loaded into memory), which improves performance with tools like [ephyviewer](https://github.com/NeuralEnsemble/ephyviewer). (What? You aren't using ephyviewer? You don't know what you're missing! Seriously, go try it, especially if you need video+ephys synchonization.)

I've spent many, many hours (8 months, on and off, actually) of quality time with AxoGraph files deciphering their poorly documented, multi-versioned, irregularly blocked binary contents, and [`axographrawio.py`](https://github.com/jpgill86/python-neo/blob/axographrawio/neo/rawio/axographrawio.py) is the result of that hard work. I was able to extract much more metadata from the files than the developer's C++ code allows.

If you work with AxoGraph files, please consider trying it out now (``pip install -U git+https://github.com/jpgill86/python-neo@axographrawio``) and letting me know if you have any problems.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
This look like a mamouth task similar to ABF files : multi version/header irregulary block aligement...
Thank you for this.
Thank you also for promoting ephyviewer :) but I think appart being the two developers we also are the two users...
Cheers,
Samuel

**Comment by jpgill86** [comment]
I just opened a pull request on GIN with some new test files. Could someone merge it so that I can run my new tests against CI?

https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/8

**Comment by jpgill86** [comment]
I have all of the remaining tasks completed in my local repo. I'm just waiting for my [GIN pull request](https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/8) to be merged before I push here so that the tests do not fail.

**Comment by jpgill86** [comment]
Thanks @apdavison for merging my test files!

Unfortunately, it seems CircleCI has trouble downloading test files with spaces in their names (but not Travis CI, weird). I've opened another pull request on GIN with changed file names. Hopefully this works better.

https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/9

**Comment by jpgill86** [comment]
Alright! All my to-dos are complete, documentation is complete, and tests are complete and passing. Let me know what you think, and if all is well then this pull request is ready to be merged!

**Comment by jpgill86** [comment]
Thank you @apdavison!!!

**Comment by jpgill86** [comment]
Would it be too much to ask for a minor release (0.7.2?) so that this new RawIO could be released?

**Comment by jpgill86** [comment]
Actually, I'm going to look into the feasibility of that first... perhaps I built this RawIO on top of some of the lazy-mode changes that won't be completely ready until 0.8.0 anyway.

**Comment by samuelgarcia** [comment]
@apdavison : @jpgill86 need a neo release for this IO quite soon for releasing another project that depend on it.

The lazy mode is already in the master. So a minor release is not possible.
Could we make a 0.8 soon by merging as many as possible PR ?

**Comment by jpgill86** [comment]
> Actually, I'm going to look into the feasibility of that first... perhaps I built this RawIO on top of some of the lazy-mode changes that won't be completely ready until 0.8.0 anyway.

My concern was unnecessary. It appears that the commits in this PR could be applied directly to the latest release, version 0.7.1, and it would still work.

Cherrypicking all these commits would only be necessary if you wanted to release AxographRawIO but none of the other changes that have been made to master since 0.7.1.

The simpler thing, of course, would be to create a release from master, but if there are changes there intended only for 0.8.0, I would understand hesitations to do that.

If the Neo maintainers prefer, I could open a new pull request that branches off of tag 0.7.1 and applies the changes here. I suppose you wouldn't want to merge the PR into master at that point (this PR has already been merged), but would instead need to create an "0.7.x" branch from which the new PR could be merged and a release could be made.

Would that be too disruptive, or could we make that work?

**Comment by jpgill86** [comment]
> Could we make a 0.8 soon by merging as many as possible PR ?

My latest suggestion wouldn't require you to rush things. If you made a maintenance branch called "0.7.x" starting at the "0.7.1" tag, I could open a new PR against that branch containing the same changes found in this PR. After merging, version 0.7.2 could be released from that maintenance branch, and the only changes between 0.7.1 and 0.7.2 would by the ones directly related to AxographRawIO.

**Comment by jpgill86** [comment]
To be clear, this is what I'm suggesting.

A Neo maintainer would create a new maintenance branch at tag `0.7.1`:
```
git branch 0.7.x 0.7.1
git push origin 0.7.x
```

I would then locally rebase the changes in this PR onto the maintenance branch
```
git branch axographrawio-backport axographrawio
git rebase c0107d axographrawio-backport --onto 0.7.x
```
where `c0107d` is the commit on master that this PR originally branched off of.

I would then open a new pull request for `axographrawio-backport` against `0.7.x`.

If tests pass, the PR could be merged into `0.7.x`, and release 0.7.2 could be created from that point.

**Comment by apdavison** [comment]
This is fine with me, we've maintained branches like this before when we've had breaking changes in master.

I've created the 0.7.x branch, so please go ahead with the rebase @jpgill86

**Comment by apdavison** [comment]
(@samuelgarcia I am also in favour of making a 0.8.0 release soon. Maybe we can have a maintainers video meeting soon to discuss this and triage the issues/PRs)

**Comment by jpgill86** [comment]
> I've created the 0.7.x branch, so please go ahead with the rebase @jpgill86

Thank you @apdavison, I will do that.

I noticed that the new branch passed tests on [Travis CI](https://travis-ci.org/NeuralEnsemble/python-neo/builds/553864845), but not [CircleCI](https://circleci.com/gh/NeuralEnsemble/python-neo/tree/0.7.x). I presume that either dependencies changed or the test files changed since 0.7.1 was released. This failure will likely show up in my new pull request. We'll find out in a few minutes...

**Pull request merged**
