### PR TITLE
Acknowledgements

### PR DESCRIPTION
**Pull request by apdavison**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
You are unlucky with circle-ci and nixio

**Comment by apdavison** [comment]
The CircleCI failure doesn't come from this PR, which only changes docs.

The failure is on the current master, and was triggered by "Merge pull request #702 from INM-6/feature/nix_write_proxyobjects"

**Comment by achilleas-k** [comment]
I did some digging last night since it's a failure in a NIXIO test.  It was introduced in PR #702 like you mentioned but that was just the test that surfaced the bug.  It's the same bug that I fixed in the regular NIXIO in PR #695, but it's coming from the NIXRawIO, which I neglected to check.

We'll get a fix out for the NIXRawIO soon.

**Comment by JuliaSprenger** [comment]
@apdavison: can you rerun CI? Somehow I don't have permission to trigger this for this PR.

**Comment by samuelgarcia** [comment]
@JuliaSprenger : same for me I don't have write to rerun circleci. Do you known why ?

**Comment by JuliaSprenger** [comment]
@samuelgarcia: Is this fork somehow protected? For some PRs I had the rights, but for others not...

**Comment by apdavison** [comment]
I think it might be because I did a force push. Since this PR doesn't change any code, only documentation, we don't actually need to run CI.

**Pull request merged**
