### PR TITLE
Indexing of AnalogSignals and IrregularlySampledSignals using numpy arrays

### PR DESCRIPTION
**Pull request by JuliaSprenger**
This PR is based on #557. In addition to #557 it implements indexing of AnalogSignals and IrregularlySampledSignals via numpy arrays. The returned object is a quantity object, as the temporal information can not necessarily be captured by an AnalogSignal or IrregularlySampledSignal.
See also #556 for the discussion.

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
@jpgill86 Is this the solution you had in mind?

**Comment by jpgill86** [comment]
@JuliaSprenger, yes, this looks good!

Since indexing into a multi-trace `AnalogSignal` could in general result in different numbers of samples per trace, I think it makes sense to raise an `IndexError` when this happens. However, for the special case where the number of samples is the same for all traces, would it make sense to add a test to `test_analogsignalarray.py`?

    def test__comparison_as_indexing(self):
        assert_array_equal(self.signal1[self.signal1 < 10],
                           np.array([[0, 1, 2, 3, 4],
                                     [5, 6, 7, 8, 9]]) * pq.nA)

**Comment by JuliaSprenger** [comment]
Yes, I agree. I added two more tests. More suggestions for improvement?

**Comment by jpgill86** [comment]
Looks good to me! 👍

**Comment by JuliaSprenger** [comment]
@samuelgarcia, @apdavison: could one of you have a look and merge if you agree to the changes?

**Comment by apdavison** [comment]
As a general point, all of the formatting changes make it difficult to review the actual important code changes. I'm not at all sure that @pep8speaks is a net positive, we should review the decision to install this at some point.

More specific to the real changes, what was the argument for going with `Quantity` rather than `IrregularlySampledSignal` as the return type? Under what conditions is an `IrregularlySampledSignal` unable to capture the temporal information?

**Comment by JuliaSprenger** [comment]
In the case of the ```IrregularlySampledsignal``` containing multiple traces in combination with arbitrary indexing, the resulting array contains entries related to different times, so it can't be represented as a (single) IrregularlySampledSignal.
Here is an example
```python
i = IrregularlySampledSignal([1,2,3] * pq.s, [[2,1],[1,1],[1,2]]*pq.V)
mask = i > 1
j = i[mask]
```
Currently a quantity array is returned containing the indexed entries.  If we strictly wanted to stick to neo objects, the only option would be to return multiple ```IrregularlySampledSignals```, which might run into more numpy related problems in the long run.

**Comment by apdavison** [comment]
ok, I was thinking only of 1D indexes, but I guess for NumPy interoperability we need to support arbitrary indexing.

**Comment by samuelgarcia** [comment]
I am back, sorry for the long silence.

Even if it is late, I am OK with this.

I also totally agree with @apdavison  that pep8 is total regression.
It is becoming very hard to understand  the real patch.
Specially in that case when few lines are involved but with a big impact.

Thanks for the work!!

**Pull request merged**
