### PR TITLE
Added an IO for IGOR Pro. Limited functionality so far.

### PR DESCRIPTION
**Pull request by apdavison**
cf #109

This PR is against the apibreak branch (0.4 dev), but the code should also work with the master branch (0.3.x) if someone wants to use it.

I will add some tests when I have time.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi,
to avoid dependency could we copy/paste the internal code of igor inside neo directly (with author autorisation ?

Samuel

**Comment by apdavison** [comment]
I don't think there is a big advantage to having the code inside Neo; it is a simple Python dependency, `pip install igor` works fine.

**Comment by samuelgarcia** [comment]
Hi Andrew.
Have you a small file to put here https://portal.g-node.org/neo/ for running tests ?

**Comment by jakirkham** [comment]
It seems `igor` last saw a new release in 2012. There is also `igor.py`, which saw a release in 2015. Though haven't evaluated other merits of the two.

**Comment by apdavison** [comment]
On the `igor.py` page it states that it has been superseded by `igor`. The 2015 'release' was apparently just to fix a typo in the README.

**Comment by apdavison** [comment]
Closing this, since the apibreak branch has been merged to master. Replaced by #251

**Pull request closed without merging**
