### PR TITLE
[neuralynx] Adjust test to match #949

### PR DESCRIPTION
**Pull request by JuliaSprenger**
Follow up of #957 to catch up with changes introduced in #949

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
rebasing after merge of #913

**Comment by samuelgarcia** [comment]
OK
Can I merge ?

**Comment by JuliaSprenger** [comment]
yes

**Comment by JuliaSprenger** [comment]
@samuelgarcia  Now test in master are passing again. Thanks for merging!

**Pull request merged**
