### PR TITLE
Fix some test failures that recently appeared on CircleCI

### PR DESCRIPTION
**Pull request by apdavison**
Some of them are due to Neo problems, one is a NumPy 1.16.0 bug

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
Thanks for taking care of this! I tested it and it works also for me. Do you want to fix PEP8 before I merge this?

**Comment by JuliaSprenger** [comment]
Sorry, I was too fast in merging. Now we have 2 trailing whitespaces in the code, but I guess we can live with that for now...

**Comment by apdavison** [comment]
sorry about the whitespace, I just changed laptops, and haven't properly configured my editor yet :-)

**Comment by samuelgarcia** [comment]
I won't tell to anybody about this 2 whitespaces.
You can count on me.

**Pull request merged**
