### PR TITLE
Local import and remove HAVE_PACKAGE logic

### PR DESCRIPTION
**Pull request by samuelgarcia**
This PR remove unnecessary import at module level and import extra dependency only when they are needed when instanciating an IO class.

See #1160

This should:
  * help in complicated environement (by not importing everything)
  * decrease import duration

The drawback:
  * it raise error only when instanciate (run time) and not at load time.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91

**Review by alejoe91 — APPROVED** [review]

**Comment by JuliaSprenger** [comment]
Hi @samuelgarcia 
Thanks for the simplifications. Did you confirm this is reducing the import time?
I think we are loosing at tiny bit of user friendliness here, but it also simplifies the code, so let's go with it.

**Comment by JuliaSprenger** [comment]
For reference: This change improves the import time on my system from 1.6s to 0.5s. @samuelgarcia It works :+1:

**Comment by samuelgarcia** [comment]
cool.
To be totaly honest I did not make benchmark :)

**Pull request merged**
