### PR TITLE
Minor Fixes to the Blackrock reader

### PR DESCRIPTION
**Pull request by rohanshah**
This pull request is equivalent to this PR that I closed: https://github.com/NeuralEnsemble/python-neo/pull/325 but with a cleaner commit history.

### CODE REVIEW

**Comment by mdenker** [comment]
Hi rohanshah, I just had a look at your fixes, thanks a lot, looks all good! I tested against our data files, and it works well. 
@apdavison I think this is fine to merge.

**Comment by rohanshah** [comment]
@apdavison do you mind merging this when you have some time? I have another pull request I'd like to make on top of these changes as well.

**Comment by mdenker** [comment]
@rohanshah Hi, actually, I also have another PR with a lot of changes to BlackrockIO waiting. Would you mind if I go ahead first? Mine is at:
https://github.com/INM-6/python-neo/tree/fix/blackrockio_issues

**Comment by rohanshah** [comment]
@mdenker sure thing! could you also let me know when your changes go out so that I can fix any merge conflicts my branch (https://github.com/NeuralEnsemble/python-neo/pull/334)?

**Comment by mdenker** [comment]
@rohanshah ok, thanks, I'll try to match my branch with your previous fixes and make the PR by the end of tomorrow -- I'll post it here then. This PR will include a lot of little fixes that accumulated from various people, but no principle major changes (except for a new keyword argument to allow to load LFPs either as discrete sampled integer values or as voltages).

**Comment by mdenker** [comment]
@rohanshah Sorry, took a bit longer than expected, since I found another bug in the unit tests. I made a PR now at #335

**Pull request merged**
