### PR TITLE
Default group mode to 'group-by-same-units'

### PR DESCRIPTION
**Pull request by samuelgarcia**
'split-all' > 'group-by-same-units'

#715
#832 
#710

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@jpgill86 
Hi Jeffrey.
I have changiing the default behavior of grouping in basefromrawio.py for signal group mode.
This has broken all your tests in axongraph so I put `blk = reader.read_block(signal_group_mode='split-all')` evrywhere.
Maybe you may want to refactor you axograph tests.
Tell me.

**Comment by jpgill86** [comment]
Hi @samuelgarcia, I'll take a look when I can, soon I hope!

**Comment by samuelgarcia** [comment]
I ppropose to merge this PR soon.
And if you want change tests you will be able to do it.
Absically I force the old befault behavior (split) in your tests.

**Comment by jpgill86** [comment]
That makes sense. No need to wait for me to merge!

**Comment by apdavison** [comment]
todo: add warning when default is used, otherwise a lot of code could break without the user understanding why.

We will keep this warning for one release - drop for 0.10.0

**Comment by samuelgarcia** [comment]
In the code wa already add this:
```
            if self._prefered_signal_group_mode == 'split-all':
                self.logger.warning("the default signal_group_mode will change from "\
                                "'split-all' to 'group-by-same-units' in next release")
```
since 1147637256cb5e473845e895f0d4d67b6ece6938 in July 2019.

So the warning cycle already accur in last release. I think there is no need to do it in the one.
@apdavison @JuliaSprenger @mdenker :  what do you think ?

**Comment by apdavison** [comment]
Decision on meeting on 07/09/2020:
  - change the default for 0.9.0
  - for affected IOs emit a warning, to be removed in 0.10.0

"affected IOs" means IOs where the default has changed and where the flag is None.

**Comment by samuelgarcia** [comment]
@apdavison @JuliaSprenger : is this warning OK ?

**Pull request merged**
