### PR TITLE
ChannelIndex.channel_names is now 'U' instead of 'S'

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This need to merged before  #824

**Comment by samuelgarcia** [comment]
@MarinManuel @JuliaSprenger : I prefer this fix for channel names.
The 'U' is now official.

**Comment by JuliaSprenger** [comment]
I think there are a still a number of places in the code, where 'S' is used instead of 'U', e.g. https://github.com/NeuralEnsemble/python-neo/blob/fce4227410249660f62ce0f3c3b596fc2cde4f68/neo/io/brainwaredamio.py#L141
These are not affecting the functionality, since the type is anyway converted later, but maybe it would make sense to systematically replace 'S' by 'U' also in all non-relevant places?

**Comment by samuelgarcia** [comment]
I think I already fix the brainwaredamio no ?
Test are passing so I think there is no channelindex.channel_names with 'S' anymore.
Each object read by IOs are tested for there types and dtypes normally.
What do you think of this solution ?

**Comment by JuliaSprenger** [comment]
Yes, you are right, I missed that one. Looks good to me!
Thanks for the fix.

**Pull request merged**
