### PR TITLE
Add Access to Intan Digital-In and Digital-Out from the RawIO API

### PR DESCRIPTION
**Pull request by zm711**
This might just be me, but I was hoping to also use Neo to obtain `digital in` information from Intan recordings. The ADC stream worked great, so I tweaked the code to allow access to digital streams as well.  Based on my local testing it worked fine and the dig-in channel is actually encoded by the height of the bar (so users could do their own post-processing to separate out into dig-1, dig-2 etc. --see attach figure with x-axis being given in samples).  I don't have any files with `dig-out` though .

I also put up a first draft of a doc-string. Happy to receive any comments. 

I know @samuelgarcia wrote the implementation so if there is a reason why you'd prefer to not include this just let me know.

image

### CODE REVIEW

**Comment by zm711** [comment]
One other possibility that I was thinking about would be to create a function like below:

```python
def _get_digitalsignal_chunk(self, i_start=None, i_stop=None):
        
        digital_memmap = self._raw_data["DIGITAL-IN"]
        dig_size = digital_memmap.size
        dig_shape = digital_memmap.shape
        
        if i_start is None:
            i_start=0
        if i_stop is None:
            i_stop =dig_size
        
        block_size = dig_shape[1]
        block_start = i_start // block_size
        block_stop = i_stop // block_size + 1

        sl0 = i_start % block_size
        sl1 = sl0 + (i_stop - i_start)

        digital_data = np.squeeze(digital_memmap[block_start:block_stop].flatten()[sl0:sl1])
        
        native_order = self._global_info['dig_native_order']
        
        digital_chunk = np.zeros((len(native_order), (i_stop-i_start)), dytpe='uint16')
        
        for value in native_order:
            digital_chunk[value, :] = np.not_equal(np.bitwise_and(digital_data,(1 << value)),0,)
            
        return digital_chunk
```

This would mirror the `analogsignal_chunk`. Then instead I would  add the `native_order` of the channels which are already obtained while parsing the header (I would add a couple lines to add them into `_global_info`.) Then we don't touch `ordered channels` which might confuse users who try to use the normal analog functions on the digital data. This function would let us  handle returning the digital without messing with mixing digital and analog.

Let me know if you'd be willing to implement something like this Sam @samuelgarcia for Neo or whether you think it's out of scope. If you like this idea better (or hate it) I'm happy to tweak the PR.

**Comment by CodyCBakerPhD** [comment]
resolves #792

@JuliaSprenger @samuelgarcia anything holding up this PR? Do you need example data for it?

**Comment by samuelgarcia** [comment]
Hi Zach.
I am ultra sorry for the long delay.
Thanks for the patch.
This OK for me in actual state but I have to admit that I would be more happy to have this
```def _get_digitalsignal_chunk(self, i_start=None, i_stop=None):```
but this need modification also in baserawio.py and add a new entry in the self.header.

So maybethe best is to merge now and postpone a bit the writting of "digitalsignal" concept.

**Comment by zm711** [comment]
@samuelgarcia 

That works for me. I have my workaround function already outside of neo, so I'm in good shape. This merging would at least allow me to stay in neo rather than hack the memory map structure.

**Comment by zm711** [comment]
I'll fix the pep8speaks.

**Comment by zm711** [comment]
Sam so long as the tests pass, I'm good with this as is. Thanks.

**Comment by samuelgarcia** [comment]
Ok. Thank you Zach.

**Pull request merged**
