### PR TITLE
Fix for loading Blackrock files of version 2.1

### PR DESCRIPTION
**Pull request by bjoern1001001**
After playing around a lot with the new BlackrockRawIO I was able to get Blackrock files of version 2.1 to load (see also issue 417). I copied some parts of the old IO over because they were referenced but not yet available and adapted them to fit into the new structure. They originally required more data being available already but this could be eliminated because the needed functionality (a lot less than the original methods had) did not require those. Using this code I was able to fully load files of version 2.1.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Thank you for this.
Have you tested with both 2.7 and 3.X ?

**Comment by samuelgarcia** [comment]
Tell me OK for merging.

**Comment by bjoern1001001** [comment]
I had thought so but I tested again and noticed the bug you seem to be referring to about str.decode() not being possible. I changed this to differ between version 2.1 and 2.2/2.3 as well. Now it should work with all python versions.
I also added additional tests for loading version 2.1 and will create a pull request for those soon.

**Comment by bjoern1001001** [comment]
In my opinion it can be merged.

**Comment by bjoern1001001** [comment]
@samuelgarcia, do you think there are any more necessary changes to this pull request or can it be merged?

**Comment by samuelgarcia** [comment]
Let's merge.

**Pull request merged**
