### PR TITLE
Add support for Biocam brw v4.x files, closes #1324

### LINKED ISSUE #1324: Support for Brainwave/Biocam 4.x file format
I'm trying to process some data that has been acquired using a Biocam acquisition system, but it seems like the formatting/metadata is not currently supported in NEO. Are there plans to add extractor support for the latest Biocam 4.x format in the near future? Thanks!

### PR DESCRIPTION
**Pull request by mahlzahn**
* ~missing: proper test file~

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks Robert! Can you generate and share a very small test file for the new format?

**Comment by mahlzahn** [comment]
> Thanks Robert! Can you generate and share a very small test file for the new format?

Hi Alessio, I will upload it and modify the concerning tests as soon as my colleague does new recordings. That should be until mid-October. (Same for https://github.com/SpikeInterface/probeinterface/pull/216)

**Comment by matbonfanti** [comment]
Hi @mahlzahn, thanks for the work you have done! My collaborators and I are looking forward to using neo with our data.
Could we help you in any way? E.g. we could record and make available a short recording for the unittest...

**Comment by matbonfanti** [comment]
thanks @mahlzahn, I have already tried your version of the code, reading a test recording from my collaborators. I can confirm it works fine (but this recording is too long to be used as test data).

**Comment by mahlzahn** [comment]
> That's great! If you send me the test files I can make a PR to gin. Let me know if instead you prefer to do it yourself!

I already prepared all and now I wait for the access rights and then I create the PR myself.

**Comment by alejoe91** [comment]
@mahlzahn you should be able to open a PR now on GIN ;)

**Comment by BptGrm** [comment]
Hi, any ETA on this ? I was trying to make my own version locally before finding this, great to see it being supported !

**Comment by alejoe91** [comment]
This should be ready for final review since @mahlzahn affed the test files too!

**Comment by BptGrm** [comment]
Just noticed that, I also had a sample uploaded to the GIN a few months back.

Any reason not to calculate the gain with the bit depth as it is for brw v3.x ?  I just get it with `bit_depth = int(np.log2(rec_vars['ValueConverter']['MaxDigitalValue']))`. They're very close numerically but on that kind of data I'm always a bit cautious.

I'll test with HerdingSpikes to see if there's the same scaling issues as with the original unfiltered neo readout.

**Comment by mahlzahn** [comment]
> Any reason not to calculate the gain with the bit depth as it is for brw v3.x ? I just get it with `bit_depth = int(np.log2(rec_vars['ValueConverter']['MaxDigitalValue']))`. They're very close numerically but on that kind of data I'm always a bit cautious.

Yes, the [brw v4.x file format documentation](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/biocam/documentation_brw_4.x_bxr_3.x_bcmp_1.x_in_brainwave_5.x_v1.1.3.pdf) explicitly states how to calculate the analog value on page 7:
```
AnalogValue = MinAnalogValue + DigitalValue * (MaxAnalogValue – MinAnalogValue) /
(MaxDigitalValue – MinDigitalValue)
```
I just followed this.

**Comment by BptGrm** [comment]
Opening, filtering and reading .brw v4.x worked just fine for me !

Still getting scaling issues as before : 

 - Through neo/SI, no filtering : 
Spike_1855

 - Through neo/SI, with bandpass filter : 
Spike_858
Spike_877

Some OK, some not, might just be saturation, hard to tell without the ability to filter in HerdingSpikes.

- Compared to HerdingSpikes with my own sort of functional reader for brw v4.x : 
Spike_14080

Will try again with another sorter to see if this is HS-specific.

**Comment by BptGrm** [comment]
The issue seems to persist, even before sorting.

I loaded one of my recording, and through SpikeInterface : 

`traces = recording.get_traces(channel_ids=['45','100','1000','2486','78'], end_frame=4096)`
`plt.plot(traces)`

Without filtering : 

raw_traces

WIth bandpass filtering : 
filtered_traces

Looks like the same 2048 scaling issue.
Would be curious to see if this is reproducible on someone else's recording to see if this could be due to some hardware/recording parameters issue.

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Hi Robert.
thank you for adding this new format version.
Sorry for the delay of merging!

**Pull request merged**
