### PR TITLE
[DOC] - Maintenance of in-code comments and docstrings

### PR DESCRIPTION
**Pull request by TomDonoghue**
As I was working through the code to familiarize myself with the module, I made a bunch of small fixes along the way. 

Included:
- first commit: typo and some wording fixes across most of the module
- second commit: standardizes usage of numpydoc format docstrings in places where it was being used

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
Thanks for adding all of those typo and layout fixes! I hope you use some automated suggestions and did not read all of this from top to bottom.

**Comment by TomDonoghue** [comment]
Definitely pretty automated! A spellchecker in my text-editor and a couple strategic searches for the docstrings covered most of it. I also did this while I was purposefully scrolling through things to get a sense of the codebase, etc, so looking through was also part of the goal!

**Comment by samuelgarcia** [comment]
thanks Tim. It looks like that you are in summer cleaning mode at several place!

**Comment by TomDonoghue** [comment]
@samuelgarcia - hahaha, yeh - I'm at the NWB user days event and using it (in part) as an opportunity to do a deep dive on several tools across the ecosystem!

**Pull request merged**
