### PR TITLE
[utils] do not copy nix_name annotation to different object types

### PR DESCRIPTION
**Pull request by JuliaSprenger**
solves #936

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Julia.
Fixing this here is OK but doing this we inject very specific IO stuf into cor/utils.
I am super happy with this.
And moreover, if a user inject annotation in between object by itself the problem will still be here.

Could it be possible instead to make "annotation cleaner" inside NixIO before writting to remove annotation that have the wrong "type" ?

**Comment by JuliaSprenger** [comment]
> Hi Julia.
> Fixing this here is OK but doing this we inject very specific IO stuf into cor/utils.
> I am super happy with this.
Did you maybe forget a `not` in this sentence?
> And moreover, if a user inject annotation in between object by itself the problem will still be here.
Yes if the user manually messes with the nix specific annotations, then the resulting nix file will be inconsistent, removing annotations of the wrong type wouldn't prevent this...
> 
> Could it be possible instead to make "annotation cleaner" inside NixIO before writting to remove annotation that have the wrong "type" ?
For now I will refactor the cleaning of the annotations into a separate utility function, then maybe when updating the nixio we can incorporate it there each time when writing to disk.

**Comment by samuelgarcia** [comment]
> Did you maybe forget a `not` in this sentence?

Yes as you guess I gorgot the negation....

> For now I will refactor the cleaning of the annotations into a separate utility function, then maybe when updating the nixio we can incorporate it there each time when writing to disk.


Ok.
Shal we merge so ?

**Comment by JuliaSprenger** [comment]
> For now I will refactor the cleaning of the annotations into a separate utility function, then maybe when updating the nixio we can incorporate it there each time when writing to disk.

I did the refactoring in this module. @samuelgarcia Does this look better to you?

**Comment by samuelgarcia** [comment]
This lookfs good.

**Pull request merged**
