### PR TITLE
spikeglx naming debug #1240

### PR DESCRIPTION
**Pull request by samuelgarcia**
#1240

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@DradeAW can you test this ?

**Comment by DradeAW** [comment]
I now have a different error:
```
recording = se.SpikeGLXRecordingExtractor(".", stream_name="imec0.ap")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 67, in __init__
    probe = pi.read_spikeglx(meta_filename)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/probeinterface/probeinterface/io.py", line 1119, in read_spikeglx
    meta = parse_spikeglx_meta(meta_file)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/probeinterface/probeinterface/io.py", line 1149, in parse_spikeglx_meta
    key, val = line.split('=')
ValueError: too many values to unpack (expected 2)
```

I'm guessing this is because of the 3rd line in the meta file containing multiple `=` signs?

**Comment by samuelgarcia** [comment]
This is in probeinterface you need to update probeinterface I think

**Comment by DradeAW** [comment]
Same problem, just the line numbers that are different:

```
recording = se.SpikeGLXRecordingExtractor(".", stream_name="imec0.ap")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 67, in __init__
    probe = pi.read_spikeglx(meta_filename)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/probeinterface/probeinterface/io.py", line 1133, in read_spikeglx
    meta = parse_spikeglx_meta(meta_file)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/probeinterface/probeinterface/io.py", line 1163, in parse_spikeglx_meta
    key, val = line.split('=')
ValueError: too many values to unpack (expected 2)
```

**Comment by samuelgarcia** [comment]
Does the neo.SpikeGLXIO working ?

**Comment by DradeAW** [comment]
Yes, both `neo.rawio.SpikeGLXRawIO().parse_header()` and `neo.io.SpikeGLXIO` seem to be working :)

**Comment by alejoe91** [comment]
I think it messes up with the `nidq` stream name...

**Comment by JuliaSprenger** [comment]
@samuelgarcia Do you mind looking into fixing also this?

**Pull request merged**
