### PR TITLE
Replace distutils.version with packaging.version

### LINKED ISSUE #1134: Deprecation Warnings with py3.9/3.10
In recent versions of Python, distutils.LooseVersion is deprectated, so this leads to a lot of warnings.

setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)

### PR DESCRIPTION
**Pull request by apdavison**
fixes #1134

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Merci Andrew!
This was an urgent need.

**Comment by samuelgarcia** [comment]
This patch make the implementation of neuralynx unhappy...

**Comment by apdavison** [comment]
yep, I'm working on that...

**Comment by JuliaSprenger** [comment]
Thanks for fixing this!

**Pull request merged**
