### PR TITLE
Backport AxographRawIO into 0.7.x maintenance branch

### PR DESCRIPTION
**Pull request by jpgill86**
See discussion in #670.

### CODE REVIEW

**Comment by jpgill86** [comment]
These changes have already been merged into master with PR #670. If a new release, 0.7.2, is created, only the release notes will need to be merged into master.

**Comment by jpgill86** [comment]
I don't know why the Travis test result still shows "Pending" when [it passed](https://travis-ci.org/NeuralEnsemble/python-neo/builds/553874226) over 10 hours ago!

[As I feared](https://github.com/NeuralEnsemble/python-neo/pull/670#issuecomment-508194241), the CircleCI tests failed, just as they did [before I created this PR](https://circleci.com/gh/NeuralEnsemble/python-neo/tree/0.7.x).

*Sigh*... 😢

**Comment by apdavison** [comment]
There were a few fixes due to new versions of numpy, matplotlib, etc. after the 0.7.1 release.

e.g. [c0107d4] and [89c2210]

I don't have time to apply those to the 0.7.x branch right now - @jpgill86 could you make a new PR to get the tests passing for 0.7.x?

**Comment by jpgill86** [comment]
Thanks @apdavison for the pointers, I'll try it!

**Comment by jpgill86** [comment]
#683 passed the tests. After it is merged, I'll rebase this PR onto it.

**Comment by jpgill86** [comment]
Ready to merge!

**Comment by jpgill86** [comment]
Thank you @apdavison! All looks good from my end. Is there anything else I need to do for the release?

**Pull request merged**
