### PR TITLE
REBASED Nlx lost segments with lost samples 

### PR DESCRIPTION
**Pull request by sin-mike**
This is just a rebased version of #693 

The previous PR became eventually broken when I had reset it and used rebase instead of merge.

### CODE REVIEW

**Comment by sin-mike** [comment]
@samuelgarcia it works!

**Comment by samuelgarcia** [comment]
Absolutly perfect.
Could youfix pep8 please ?

**Comment by samuelgarcia** [comment]
Thank you very much for this tedious pep8.
I will merge this as soon as test pass and so will be 0.8.

**Comment by samuelgarcia** [comment]
This close #693.

**Pull request merged**
