### PR TITLE
Good channel order for old openephys format.

### PR DESCRIPTION
**Pull request by samuelgarcia**
In old implementation channel order was not the natural one.
"CH" channels where put after the "ADC" channels. This was the total inverse of the sofwtare.
This put the good order.

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
Hi @samuelgarcia,
the new implementation is definitely more readable than the old one. However, it's not clear to me why the IO should reorder the channels if they were stored in a particular order in the file. The information which channel the data originated from was also already accessible before, right?

**Comment by samuelgarcia** [comment]
It is a several file data format.
In the previous implementation the order was bad. (I did it).
The order was not corresponding to the sofwtare. it was not a poblem becuase it was 2 distinct AnalogSignal (2 groups).
But this could leave to problem when making the electrode probe location with probeinterface and PRB files.
This new order is the good one.

**Comment by JuliaSprenger** [comment]
@samuelgarcia Do you plan to also include a test for this one or is this PR complete from your side?

**Comment by samuelgarcia** [comment]
Honestly, it was not my plan but if it is too shocking I can try.

**Comment by JuliaSprenger** [comment]
@samuelgarcia this could turn into a showcase PR ;)

**Comment by samuelgarcia** [comment]
héhéhéhé.

**Comment by samuelgarcia** [comment]
I could not leave a PR without tests.
I must be exemplary.
It is done now.

**Comment by JuliaSprenger** [comment]
Thanks for adding a test! I will merge now.

**Pull request merged**
