### PR TITLE
0.13.4 Release

### PR DESCRIPTION
**Pull request by zm711**
Feel free to start proofing. Just wanted to get this started in particular I started editing the codemeta json, but then the links will be wrong until I actually do the release, so maybe I fix those in an after release?

I updated all PRs and issues tagged as 0.14.0 back down to 0.13.4.

### CODE REVIEW

**Comment by zm711** [comment]
zugbruecke is seg faulting in the CI. I'll need to dig into this later. Might be too busy, but I'll see what I can do soon.

**Comment by apdavison** [comment]
concerning codemeta, probably best to set "downloadUrl" to `null`, so as not to have an inconsistent state with a mix of information from different versions.

**Comment by zm711** [comment]
Sounds good. Thanks Andrew! Will fix that soon :)

**Comment by zm711** [comment]
Since 3.13 only officially works with Numpy 2+ do we want to pin python for this point release? 
python > 3.9 < 4.0? @apdavison @samuelgarcia @alejoe91

**Comment by zm711** [comment]
Also some Maxwell test failures. We recently merged the maxwell PR #1579? @alejoe91 any read on this?

**Comment by zm711** [comment]
Turns out med_dhn_py released a new version 2.0.0 on 10OCT24 (https://pypi.org/project/dhn-med-py/), which seems to be causing seg faults. Let's limit until they have stabilized 2.0.

**Comment by zm711** [comment]
* [ ] Add in edf PR
*  [ ] Add in copy-dep PR
 * [ ] Add in Plexon overflow PR

**Comment by zm711** [comment]
@samuelgarcia,

rewrote docs to incorporate first buffer api change, and quantities stuff. So please re-review now that there is a lot more.

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Merci Zach tu es notre nouveau leader.

**Pull request merged**
