### PR TITLE
Fixes for cheetah v5.4.0

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
This request incorporates changes to handle headers from Cheetah v5.4.0. Also better error recovery and messages when new header styles that are not understood are encountered.

This also handles the type of variability in the time gaps between records in a contiguous section which can arise when the sampling rate is quite low, like 1017 Hz. 

This resolves issue #906 

This will not pass tests until PR # 32 in ephy_testing_data is incorporated at gin-g.node.

### CODE REVIEW

**Comment by PeterNSteinmetz** [comment]
Two W204 PEP8 warnings to be ignored.

**Comment by apdavison** [comment]
Note that PR # 32 in ephy_testing_data at gin-g.node was replaced by [# 35](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/35)

**Comment by PeterNSteinmetz** [comment]
Looks like the circleci tests are failing because the test data for Cheetah 5.4.0 is not yet in the gin repository.

**Comment by samuelgarcia** [comment]
This is strange the file is in gin:
https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuralynx/Cheetah_v5.4.0

Note that the old [PR](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/32) you did on gin is not deletable.
And have been replace by another one by Julia.

**Comment by PeterNSteinmetz** [comment]
Maybe the CircleCI tests need to be restarted again? That looks like the correct file. It is truncated and was committed simply using git, no annexing needed.

**Comment by JuliaSprenger** [comment]
Yes, I restarted the test.

**Comment by PeterNSteinmetz** [comment]
These changes seems to pass the tests locally, so I assume it has to do with some problem with integrating the files in gin and CircleCI. Looks like it is now hanging on a timeout somehow?

**Comment by PeterNSteinmetz** [comment]
Looks like this is now passing. Will likely need the squash commit as well. It is becoming staler as time goes by and will now need #968 to handle the later changes in #949.

**Comment by JuliaSprenger** [comment]
I don't think this one should be affected by #949 as it does not interact with the baserawio specifications. Now I have to fix it in #968  if there's still incompatiblities that I didn't consider yet.

**Pull request merged**
