### PR TITLE
Improve consistency between Epoch, Event and SpikeTrain

### PR DESCRIPTION
**Pull request by apdavison**
* all can be created with lists (provided the units parameter is provided), not just with arrays
* `obj.__getitem__` with a scalar argument returns a Quantity
* `obj.__getitem__` with a slice or array argument returns an object of the same type

cf #490

### CODE REVIEW

**Comment by samuelgarcia** [comment]
OK for me.

A question unrelated to this PR:
  * obj._durations is not removed when \_\_getitem\_\_ ?.

**Comment by apdavison** [comment]
> * obj._durations is not removed when __getitem__ ?.

Probably it should be, I was just being lazy.

**Comment by samuelgarcia** [comment]
Can we merge this ?

**Comment by JuliaSprenger** [comment]
@bjoern1001001: Is this compatible with your ideas from a couple of month ago?

**Comment by bjoern1001001** [comment]
@JuliaSprenger Yes, the described behavior is what I had in mind. 

I just had a quick look on the code, and I noticed a few things I'm not sure about:

- Why is there no _copy_data_complement after event.py line 227? Currently if a slice is provided, labels will not be copied in Event, only a reference is given to the new object. I think the expected behavior is creating a copy.
- Are labels and durations correctly sliced even after doing _copy_data_complement? (epoch.py line 209)

I did not go into depth here, so maybe my points are not valid, I just wanted to raise them and make sure you are aware.

**Comment by apdavison** [comment]
@bjoern1001001 thanks for the feedback, and for spotting the missing `_copy_data_complement` in Event.

Note that labels and durations are no longer handled by `_copy_data_complement` (since #659 was merged), they are handled explicitly.

**Comment by bjoern1001001** [comment]
Ah, thank you, I was not aware of that.

This means, however, that if `obj.__getitem__` is called with a slice or array argument, none of the array attributes (`times`, `labels`, `durations`) are copied in the current implementation. Instead, numpy will create views into these arrays. So, if an Event is sliced, and labels of the returned object are altered, the original Event will be changed, too. 
I think general consensus was to always copy when slicing, that's why the `array_annotations` are explicitly deepcopied here, and #668 does this explicitly for time_slicing.

**Comment by apdavison** [comment]
hmmm, we seem to be in a mess with the copy vs view thing. One of the guiding principles of Neo is that data objects should behave the same way as plain NumPy arrays unless there is a good reason not to. Slicing an array gives a view; the same should be true (and is at present) for AnalogSignal, SpikeTrain, Epoch, Event, etc.

I think I wasn't thinking broadly enough when I merged #668. We decided to do a thorough review of objects lifecycles for the 0.9 release, so I suggest we merge this PR (which does increase the consistency of Event and Epoch wrt SpikeTrain and AnalogSignal, even if there are still inconsistencies within Neo more generally), and continue this discussion in a new ticket. For 0.9, we need to add a page to the documentation which explicitly describes the expected behaviour when slicing, shallow or deep copying, merging, concatenating, etc.

**Comment by bjoern1001001** [comment]
I agree. This PR should be merged like this and the whole issue of copying or not should be discussed in depth on its own.

**Pull request merged**
