### PR TITLE
Some improvements to AsciiSignalIO

### PR DESCRIPTION
**Pull request by apdavison**
in preparation for working on #579. Main changes:

(1) moved most arguments from `read_segment()` method to the IO class constructor, and added a `read_block()` method. This makes AsciiSignalIO more consistent with other Neo IOs.
(2) added an argument "multichannel", to control whether to create a multi-channel AnalogSignal or a list of single-channel signals. The default is the latter, for backwards compatibility.
(3) more consistency checks on argument values
(4) fixed a bug with "genfromtxt" where usecols would be applied twice.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi @apdavison 

Some comments:
  * The ci cache is also for the test file download. This mean that each time there is a problem with files
    and we want to download all of then again we also need to hack this cache key
  * In BaseFromRaw.read_segment/read_block there is a karg ```signal_group_mode= 'split-all'``` or
      ```signal_group_mode= 'all-in-one'```. Than have the same meaning as ```multichannel=True/False```

Otherwise this is OK for me.

**Comment by apdavison** [comment]
There is a separate cache for the test file download; it is only the "installed packages" cache which is involved here.

I will change `multichannel` to `signal_group_mode` for consistency.

**Comment by samuelgarcia** [comment]
> There is a separate cache for the test file download; it is only the "installed packages" cache which
> is involved here.

Sorry for this bad information.

**Comment by apdavison** [comment]
Anyone have time to merge this?

**Pull request merged**
