### PR TITLE
Added descriptions and annotations for BlackrockIO

### PR DESCRIPTION
**Pull request by bjoern1001001**
This adds Block description, Unit description (including channel_id, unit_id and unit_tag), and description for ChannelIndex for AnalogSignal.
This also solves the problem that unit_tags were the same for all Units because the local variable unit_id was not set.

Apart from that this adds back the nsx value for AnalogSignal annotations.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Outch. The big PEP8 clean break the compatibility with the master.
Sorry for not having merged before.
Could rebase on the actual master ?

**Comment by bjoern1001001** [comment]
Updated

**Comment by samuelgarcia** [comment]
@bjoern1001001 : I am sorry. there is a new conflict again with the master
```
<<<<<<< misc_annos_blackrock
                anasig_an['file_origin'] = self.filename + '.ns' + str(self.nsx_to_load)
                anasig_an['nsx'] = self.nsx_to_load
                chidx_ann = self.raw_annotations['signal_channels'][c]
                chidx_ann['description'] = 'Container for Units and AnalogSignals of ' \
                                           'one recording channel across segments.'
=======
                anasig_an['file_origin'] = self._filenames['nsx'] + '.ns' + str(self.nsx_to_load)
>>>>>>> master
```

Do you prefer this
                anasig_an['file_origin'] = self.filename + '.ns' + str(self.nsx_to_load)
or this
                anasig_an['file_origin'] = self._filenames['nsx'] + '.ns' + str(self.nsx_to_load)

(I can fix)

**Comment by bjoern1001001** [comment]
I updated it, should work now.

**Comment by samuelgarcia** [comment]
OK thanks a lot. I merge.

**Pull request merged**
