### PR TITLE
Add NESTSpikeIO and NESTMultimeterIO

### PR DESCRIPTION
**Pull request by apdavison**
building on work by @JuliaSprenger, Maximilian Schmidt, Johanna Senk, Jakob Jordan

### CODE REVIEW

**Comment by apdavison** [comment]
@JuliaSprenger I made some extensions to the `nestio` code I originally received. Do you have an updated version of that? If not, please could you review this PR?

**Comment by JuliaSprenger** [comment]
Johanna (@jhnnsnk) and I actually implemented an extended version of the nestio, which we are currently testing (https://github.com/INM-6/python-neo/tree/feature/gdfio2.0). Our version can handle gdf as well as dat files and includes a number of tests based on nest-generated test files. A PR will follow in the next days.
I suggest we compare the 2 PRs then and include the best features of both in the final version.

**Comment by JuliaSprenger** [comment]
@jhnnsnk, @apdavison. I just opened the other PR including our version of the nestio (PR #301) and the checks have passed. How should we proceed?

**Comment by apdavison** [comment]
Closing in favour of #301

**Pull request closed without merging**
