### PR TITLE
BiocamRawIO: Fix case where slice is given to `get_analogsignal_chunk`

### PR DESCRIPTION
**Pull request by zm711**
@h-mayorquin I was wrong, haha. We give a slice in spikeinterface which broke this :) 

@alejoe91, I don't have a biocam file easily available do you? I could test this, tonight with my personal laptop or we could merge and see what happens with full tests on SpikeInterface?

### CODE REVIEW

**Comment by zm711** [comment]
Give me a second I need to fix for array too. Will ping you when ready.

**Comment by zm711** [comment]
Okay the biocamrawio passed tests now. This is ready for review and we can merge after all tests merge or after one of us tests locally that passing a slice(None) is fine now.

**Review by alejoe91 — DISMISSED** [review]

**Comment by zm711** [comment]
@alejoe91 one question since you and Sam know this better. Would it ever happen in spikeinterface to generate a non-None slice that we need to worry about? I could add something for that if it would actually happen.

**Comment by alejoe91** [comment]
I don't think this is the case, because the segment `channel_indexes` are almost always called by the recording wrapper. However, it is possible to access the segment and call the `get_traces()` directly.

A simple fix could be the following:
```
if channel_indexes is None:
    channel_indexes = [ch for ch in range(self._num_channels)]
elif isinstance(channel_indexes, slice):
    start = channel_indexes.start or 0
    stop = channel_indexes.stop or self._num_channels
    step = channel_indexes.step or 1
    channel_indexes = [ch for ch in range(start, stop, step)]
```

**Comment by h-mayorquin** [comment]
Maybe you should have a test for this here?

**Comment by zm711** [comment]
That's a fair fix. Let me do it!

I thought about that, but then I was worried about what if Neo wasn't actually read for that. So I think it should be a separate PR to add that test in.

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Ok let's give this a try!

**Pull request merged**
