### PR TITLE
To fix bug 533

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
Is this PR complete? Would it make sense to add a test covering this?

**Comment by samuelgarcia** [comment]
I will fix PEP8.
I don't have idea a case for testing, it was a missintepreting of format specifications.

**Comment by JuliaSprenger** [comment]
So if we have test files with different format specifications we could test this, no?

**Comment by samuelgarcia** [comment]
I think we already have theses files.
We could test them against the real magnitude given by clampex but I don't have this software and it run only on windows. So the extra work for this bug is high compared to the patch.

**Comment by JuliaSprenger** [comment]
Ok, then we can merge this?

**Comment by samuelgarcia** [comment]
Yes, I have just push pep8 fixes.

**Comment by samuelgarcia** [comment]
Maybe we can wait for @Emerson207 and @lbologna if the patch fix there magnitude problem.

**Comment by lbologna** [comment]
Hello,

thanks for the fix.
I am testing it right now.
I'll be back soon with a feedback on how it behaves on our data.

**Comment by lbologna** [comment]
This worked for me!
Thank you.

**Comment by Emerson207** [comment]
Hello!
I tested the fix and it worked as well.
Thank you!

**Pull request merged**
