### PR TITLE
First draft of proposal for documentation rewrite

### PR DESCRIPTION
**Pull request by apdavison**
See https://neo.readthedocs.io/en/new-docs/

Main features:
- custom template for home page, with different entry points for different user needs
- use Sphinx IPython extension to ensure code snippets are always up-to-date
- use sphinx-gallery for examples
- a lot of topics rewritten from scratch, others updated

Todos:
- [ ] adding more examples notebooks @JuliaSprenger 
- [x] change to more modern theme @apdavison 
- [ ] update rawio documentation @samuelgarcia 
- [ ] review and revise all docstrings @apdavison @JuliaSprenger 
- [ ] add TOC (add toc.rst and add it to index) @apdavison 
- [x] add 4th row of entry points (examples, TOC, ...) @apdavison 
- [ ] introduce tests based on example code (optional)
- [ ] add icons to entrypoints if appropriate @apdavison 
- [ ] usability survey @mdenker

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Yeah. You are our hero.
You will have a look soon for feeback.

**Comment by JuliaSprenger** [comment]
Hi @apdavison Thanks for getting this started. I added some more changes on top of yours in #1179 and am still adding to this. If you prefer to only have a single dev branch for the new doc you can also already merge #1179.

**Comment by JuliaSprenger** [comment]
Some suggestions for what parts of the (developer) documentation needs improvement can also be found [here](https://github.com/NeuralEnsemble/python-neo/pull/1241#issuecomment-1490828764)

**Comment by apdavison** [comment]
I've switched to pydata_sphinx_theme, which I think looks much nicer. While there are still things to be improved, I think we should merge this now, if you're happy with it, and create a separate issue for each of the desired improvements.

https://neo.readthedocs.io/en/new-docs/index.html

**Pull request merged**
