### PR TITLE
Fix multiples errors in BaseFromRaw.read_block()

### LINKED ISSUE #940: BaseFromRaw.read_block(create_group_across_segment=True) fails due to multiple errors
I ran the following code on a Blackrock dataset (`i40703-001-03.nev` - published [here](https://gin.g-node.org/INT/multielectrode_grasp/src/master/datasets):

```python
from neo.io.blackrockio import BlackrockIO
filename = "i140703-001-03.nev"
bl_io = BlackrockIO(filename)
block = bl_io.read_block(create_group_across_segment=True)
```
and got the following error:

```python
~/work/juelich/repositories/python-neo/neo/io/basefromrawio.py in read_block(self, block_index, lazy, create_group_across_segment, signal_group_mode, load_waveforms)
    154             st_groups = []
    155             for c in range(unit_channels.size):
--> 156                 group = Group(name='SpikeTrain group {}'.format(i))
    157                 group.annotate(unit_name=unit_channels[c]['name'])
    158                 group.annotate(unit_id=unit_channels[c]['id'])

UnboundLocalError: local variable 'i' referenced before assignment
```
I also tried the following variation, by passing a dict instead of a bool to the argument:

```python
from neo.io.blackrockio import BlackrockIO
filename = "i140703-001-03.nev"
bl_io = BlackrockIO(filename)
block = bl_io.read_block(create_group_across_segment={"SpikeTrain": True})
```
which yielded the following error:

```python
~/work/juelich/repositories/python-neo/neo/io/basefromrawio.py in read_block(self, block_index, lazy, create_group_across_segment, signal_group_mode, load_waveforms)
    136 
    137         # Group for AnalogSignals
--> 138         if create_group_across_segment['AnalogSignal']:
    139             all_channels = self.header['signal_channels']
    140             channel_indexes_list = self.get_group_signal_channel_indexes()

TypeError: 'set' object is not subscriptable
```

On fixing the two errors above, a third error occurs on running the last piece of code:

```python
~/work/juelich/repositories/python-neo/neo/io/basefromrawio.py in read_block(self, block_index, lazy, create_group_across_segment, signal_group_mode, load_waveforms)
    159                 unit_annotations = self.raw_annotations['unit_channels'][c]
    160                 unit_annotations = check_annotations(unit_annotations)
--> 161                 group.annotations.annotate(**unit_annotations)
    162                 bl.groups.append(group)
    163                 st_groups.append(group)

AttributeError: 'dict' object has no attribute 'annotate'
```

The three errors have trivial fixes, for which I have a PR ready. After fixing these, the code seems to run smoothly.

### PR DESCRIPTION
**Pull request by shashwatsridhar**
Fixes #940.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Shash.
Thank you for this.
All theses errors or from me.
Sorry :)

**Comment by samuelgarcia** [comment]
Changes seems ok.

The bad news is that we did not have tests to check this.
Would you be OK try to put tests.
Maybe in neo/test/iotest/common_io_test.py `BaseTestIO`
by adding a method that check if the reader hinerits BaseFromRaw and try to `create_group_across_segment` cases.

**Comment by shashwatsridhar** [comment]
Hey Samuel!
I'll try and add a test, yep :) but it might take a few days till I can get to it, and I might bug you with questions if I get stuck somewhere, though 😅

**Comment by shashwatsridhar** [comment]
@samuelgarcia 

I wrote a test (which I have now pushed to this PR), but I am not sure if I am on the right track here. Could you take a quick look?

Also, all tests for, for example, the blackrockio module fail with this error (including the test I have written):

```python
test_create_group_across_segment (neo.test.iotest.test_blackrockio.CommonTests) ... /tmp/files_for_testing_neo/blackrock/blackrock_2_1/l101210-001

Error
Traceback (most recent call last):
  File "/home/shashwat/miniconda3/envs/neo/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/shashwat/miniconda3/envs/neo/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/home/shashwat/miniconda3/envs/neo/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/test/iotest/common_io_test.py", line 541, in test_create_group_across_segment
    for obj, reader in self.iter_objects(target=Block,
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/test/iotest/tools.py", line 331, in iter_read_objects
    for obj_reader, path, ioobj in iter_generic_readers(ioclass, filenames,
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/test/iotest/tools.py", line 227, in iter_generic_readers
    for ioobj, path in iter_generic_io_objects(ioclass=ioclass,
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/test/iotest/tools.py", line 148, in iter_generic_io_objects
    ioobj, path = create_generic_io_object(ioclass, filename=filename,
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/test/iotest/tools.py", line 116, in create_generic_io_object
    ioobj = ioclass(filename=filename)
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/io/blackrockio.py", line 17, in __init__
    BaseFromRaw.__init__(self, filename)
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/io/basefromrawio.py", line 75, in __init__
    self.parse_header()
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/rawio/baserawio.py", line 149, in parse_header
    self._parse_header()
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/rawio/blackrockrawio.py", line 288, in _parse_header
    spec = self.__nsx_spec[nsx_nb] = self.__extract_nsx_file_spec(nsx_nb)
  File "/home/shashwat/work/juelich/repositories/python-neo/neo/rawio/blackrockrawio.py", line 793, in __extract_nsx_file_spec
    nsx_file_id = np.fromfile(filename, count=1, dtype=dt0)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Is this a known problem?

Thanks!

**Comment by shashwatsridhar** [comment]
I think I found a more elegant solution. I created test cases and corresponding expected outcomes (such as expected errors), and the code checks if the expected outcomes are achieved. If the IO class has overridden the `read_block()` method and no longer accepts the `create_group_across_segment` argument, the IO is not tested (for example, nixio_fr).

These changes are reflected in the most recent push.

However, the issue i mentioned in the previous comment still persists. It looks like the file `/files_for_testing_neo/blackrock/blackrock_2_1/l101210-001` causes all blackrockio tests to fail. Could the file be somehow corrupted? Do you also have the sam issue?

**Comment by samuelgarcia** [comment]
Hi Shash.
Mille mercis.
This looks good to me.
Does the test is still faling for blacrock ?

**Comment by shashwatsridhar** [comment]
Hey Samuel!
Whatever you did has solved the problem - the tests no longer fail for blackrockio :)

Guess this PR is good to merge?

**Review by JuliaSprenger — APPROVED** [review]

**Comment by samuelgarcia** [comment]
ok lets merge this.
thanks.

**Pull request merged**
