### PR TITLE
[NeuralynxRawIO] Pre4 files tests

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
This pull request activates the full test suite for the PRE4 file type for Cheetah version 4.0.2. 

It also corrects an older off by one bug in test_neuralyxio.py which was omitting the last sample in each record during testing. 

This will not run integration tests until ephy_testing_data PR#20 is merged.

### CODE REVIEW

**Comment by PeterNSteinmetz** [comment]
As before, I am wondering if strict PEP8 compliance is required in python-neo? Most of these line break and remaining indentation complaints won't look very good. Would rather just leave them as is.

**Comment by apdavison** [comment]
re PEP 8: I don't think any of us worry about W504 or E126, so for me it's ok not to fix those

**Comment by PeterNSteinmetz** [comment]
Now that the test data is merged in ephy_testing_data I think the tests will pass if restarted.

**Comment by samuelgarcia** [comment]
I have just rerun travis to see.

**Comment by PeterNSteinmetz** [comment]
It looks like the Travis build is ok. But the errors showing up in the circleci tests have to do with hdf5io . Puzzling as nothing in these commits touches that io. How to fix?

**Comment by JuliaSprenger** [comment]
Yes, the h5py checks will be fixed by #893. I will rerun the tests here once #893 is merged.

**Comment by PeterNSteinmetz** [comment]
I guess this should now work if CirclCI is started since PR#893 has been merged.

**Comment by PeterNSteinmetz** [comment]
Going to wait for PR#888 to be merged before trying to rebase or merge this with current master.

**Comment by PeterNSteinmetz** [comment]
Closed and incorporated into new PR.

**Pull request closed without merging**
