### PR TITLE
Fix micromed label encoding.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
Hi @samuelgarcia,
do we have a test file for these changes?

**Comment by samuelgarcia** [comment]
Hi Julia.
Unfortunatly not.
Micromed is a medical system and I am not allow to push data from patient.
I tested it locally.
This kind of change of to be merge without CI warranty.

**Comment by JuliaSprenger** [comment]
Ok, then we have to trust you blindly here...

**Comment by samuelgarcia** [comment]
:)
Thank you.

**Pull request merged**
