### PR TITLE
Reenable Filtering Events and Epochs by Labels

### PR DESCRIPTION
**Pull request by Kleinjohann**
in the tests of the utils module filtering events and epochs using labels or any other regular attributes is not covered. #659 broke filtering by labels, but this wasn't noticed of course since the tests are missing. 

I fixed filtering by labels and added tests for labels and regular attributes.

### CODE REVIEW

**Comment by Kleinjohann** [comment]
I noticed some issues in the examples in the docstrings of `get_events` and `get_epochs` and fixed them as well.

**Comment by JuliaSprenger** [comment]
Looks good to me, if there is no further comments I would like to merge soon.

**Comment by samuelgarcia** [comment]
I don't remember.
This feature was present and then remove and here it is back ?
ok for me.

**Comment by JuliaSprenger** [comment]
This feature was automatically covered when labels were handled as `array_annotations`. Since the reversion of this, labels were not handled properly here.

**Pull request merged**
