### PR TITLE
Added recommended attributes to elphyio spiketrain

### PR DESCRIPTION
**Pull request by dguarino**
Hi,
just added the possibility to read t_start, waveforms and sampling_rate from elphy files in neo format.
I tested it against the old files and a new one, passing the baseio tests.

Thanks for considering the modifications!

### CODE REVIEW

**Comment by apdavison** [comment]
Domenico: what is the current status of this pull request?

**Comment by dguarino** [comment]
I checked: elphyio does not expose Event, Epoch, and Spike objects.
So, we can merge the current status of elphyio.

I'm (slowly) rewriting from scratch elphyio to have it lighter and cleaner... I hoped it was faster. For the moment we will stick to this code.

**Comment by dguarino** [comment]
I tried to squash my commits into one (as suggested by rproepp), but i get too many conflicts (probably because i was working always on the master branch).

As a guide in the process, I am using gitready (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). And in there they discourage the squash, when the commit has been pushed to a remote repository, precisely because of shared history.

I'm afraid of messing up the codebase if I try to resolve the conflicts by hand...
Can we just keep these commits as they are?
Any suggestions?

**Comment by samuelgarcia** [comment]
Hi domenico.
Do you think we can safetly merge that code ?
Github propose now magic squash : https://github.com/blog/2141-squash-your-commits
Was squash the only only reason of not merging. I don't remember.

**Comment by dguarino** [comment]
Yes, the only reason for squashing was to clean up the history.
There were no new changes to the code.

**Comment by samuelgarcia** [comment]
@apdavison : I guess we can merge and use the magic squash from github no ?

**Comment by samuelgarcia** [comment]
I guess that this branch needs new refactoring to be integrating in the new master.

**Comment by samuelgarcia** [comment]
@dguarino: is that branch dead ?

**Comment by dguarino** [comment]
Yep. the mods were already merged, together with others.

**Comment by samuelgarcia** [comment]
So lets close this.

**Pull request closed without merging**
