### PR TITLE
Neuroscope: fix scale of signals.

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
Need to multiply not divide by 1000 for mV scale.

### CODE REVIEW

**Comment by zm711** [comment]
Do you have some documentation or some example traces? This seems reasonable, but it would be nice to know where the scale is coming from.

**Comment by PeterNSteinmetz** [comment]
The only thing this corrects is the scaling factor applied to convert to mV from the raw samples. There is nothing in the .dat files. The corresponding .xml files contain the voltage range, number of bits for each sample, and amplification. There is nothing per se in those files which says it is mV. 

I can tell you however that with the correction the other way, as before this change, the recordings are being shown as in the 100 nV range, which makes no sense for neurophysiological signals.

This is a common mistake and I have done it myself many times - dividing instead of multiplying by the amplification. 

This change also includes a comment which clearly explains the derivation of the scale.

**Comment by zm711** [comment]
Since @samuelgarcia wrote this I put him to review it. My only suggestion would be to move the comment into the actual class rather than in the test so that future us see it there :)

**Comment by PeterNSteinmetz** [comment]
OK. I added a comment in the source and clarified that this is the proper scale to convert a raw sample value to mV.

**Comment by samuelgarcia** [comment]
Oups.
Yes it was a mistake. Thanks for the catch.

**Comment by PeterNSteinmetz** [comment]
OK. Can we get this reviewed and merged? I don't like keeping these branches open unnecessarily on my fork. Thanks.

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
