### PR TITLE
Adapt to API change of h5py version 3.0

### PR DESCRIPTION
**Pull request by JuliaSprenger**
Currently hdf5io unittests are broken due to an update in the h5py API.

This PR fixes the IO by extending the first fix implemented in #892

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Cool.
Shall we also check the version when importing ?

**Comment by JuliaSprenger** [comment]
I added a minimal requirement of h5py version 2.6 which is 4 years old, as at least locally this seemsstill compatible with the new implementation.

**Comment by JuliaSprenger** [comment]
Finally travis tests finished. Ready from my side.

**Comment by JuliaSprenger** [comment]
@samuelgarcia Any more suggestions for improvements?

**Comment by samuelgarcia** [comment]
What I saw everywhere is that this HDF5 version 3.0 broke lot of libs.
Maybe we should have 2 envs in circle-ci one with version 2.6 and one with version 3.0.
What do you think ?

Is it the only faillure we have ?

**Comment by JuliaSprenger** [comment]
I think we should merge this now as this is currently breaking the master branch and add a circleci coverage with h5py==2.6 in another PR.

**Comment by samuelgarcia** [comment]
OK I merge

**Pull request merged**
