### PR TITLE
[WIP] Deep copy annotations when using time_slice

### PR DESCRIPTION
**Pull request by JuliaSprenger**
This aims at issue #536 by ensuring a deep copy of the annotation dictionary when using time_slice

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@JuliaSprenger do you plan this for 0.7 ?

**Comment by JuliaSprenger** [comment]
I won't have time to work on this in the coming days. If anybody feels bored you can take over. Otherwise we have to postpone this. Sorry :/

**Comment by bjoern1001001** [comment]
@JuliaSprenger, @apdavison, Doesn't #668 implement all the intended changes?

**Comment by JuliaSprenger** [comment]
I checked #668 and this covers all the cases I had in mind for this PR. So I will close this one now.

**Pull request closed without merging**
