### PR TITLE
np.isin -> np.in1d. Fixes #559

### LINKED ISSUE #559: AttributeError: module 'numpy' has no attribute 'isin'
Hi,
I'm using miniconda + intel python. The current intel numpy is 1.12, but `numpy.isin` didn't get added until 1.13. The only place np.isin is used in this repo, that I could find, is [here](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/blackrockrawio.py#L1107).

I think that in this case the arrays are both 1d, so `np.in1d` should substitute just fine.

Let me know if you want me to make a PR, but for such a small change I'd prefer if one of the devs made the change directly.

### PR DESCRIPTION
**Pull request by cboulay**

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
@cboulay. Thanks for noticing. I wasn't aware ```np.isin``` is a relatively new function.
Could you rebase against master to incorporate the fixes which should fix the travis tests failing here?

**Comment by cboulay** [comment]
Rebase is done. Before rebasing I merged in master. This passed all checks (except PEP8 line too long). I expect the rebase to pass all checks too.

**Comment by JuliaSprenger** [comment]
Thanks for rebasing! We will have to fix the PEP8 issues in another PR some time.

**Comment by samuelgarcia** [comment]
Thanks.

**Pull request merged**
