### PR TITLE
Implement AxographIO module with tests

### PR DESCRIPTION
**Pull request by will-hart**
This PR proposes an IO class for reading from AXGX and AXGD files using [`axographio`](https://github.com/CWRUChielLab/axographio). It provides an alternative to `StimfitIO` for importing axograph files which may be a bit easier to get up and running, particularly on Windows.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@will-hart: thank you very much for this PR.

  * Could you  add the testing file you have in https://web.gin.g-node.org at the good place ?
  * axographio python module seems to be easy to install with pip, so maybe we could add this module in cicle-ci so a full test of this module would be done.

**Comment by will-hart** [comment]
Yes, I've had some trouble signing up to `gin` as my University account thinks the email is spam and blocks it for more than 3 hours, meaning the activation link expires :) I'll upload the file as soon as I can make an account. I'll also sort out the PEP8 fixes. 

I'm not sure about the code coverage reducing - have I messed up the tests somehow?

**Comment by will-hart** [comment]
Thanks @cgars

PR for the test files: https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/3.

**Comment by JuliaSprenger** [comment]
The axographio tests are currently not running on circle ci due to the missing axograph installation. This PR https://github.com/will-hart/python-neo/pull/1 should fix this. @will-hart: can you give it a try?

**Comment by jpgill86** [comment]
As the current maintainer of [axographio](https://github.com/CWRUChielLab/axographio), I'm excited by this and am eager to see it in the next release of Neo.

Currently two tests are failing for both **ci/circleci: test-2.7** and **ci/circleci: test-3.6**:

- `FAIL: test_IrregularlySampledSignal_repr (neo.test.coretest.test_irregularysampledsignal.TestIrregularlySampledSignalProperties)`
- `FAIL: test__repr (neo.test.coretest.test_spiketrain.TestPropertiesMethods)`

I'd like to help, but it's not clear to me that either of these relate to `neo.io.AxographIO`. Is the issue elsewhere?

**Comment by JuliaSprenger** [comment]
Hi @jpgill86, I agree it's a bit weird these seemingly unrelated tests fail by adding axographio to the requirements. I suspect there are additional changes in other package versions coming with it and thus failing these tests, but I haven't had time to look into this. It's on my todo list, but I can't promise anything.

**Comment by jpgill86** [comment]
I discovered a couple bugs in the `AxographIO` implementation and have opened a pull request with fixes: will-hart#2. @will-hart, can you verify and merge?

**Comment by will-hart** [comment]
Done, thanks for taking a look at the PR!

**Comment by jpgill86** [comment]
I think PR will-hart#3 should resolve these failing tests. Looking forward to seeing AxographIO in a Neo release!

**Comment by jpgill86** [comment]
Great, **ci/circleci: test-2.7** and **ci/circleci: test-3.6** are passing when once they were failing, but now **continuous-integration/travis-ci/pr** is failing when once it was passing!

The problem seems to be isolated to the Python 3.5 build in TravisCI. I can't imagine what might be going on, but I'll take another look.

**Comment by jpgill86** [comment]
I've characterized the problem I described above in a new issue: https://github.com/NeuralEnsemble/python-neo/issues/556

This seems to be an issue either with Neo's master branch or with NumPy, but not with this PR nor with axographio.

**Comment by will-hart** [comment]
@jpgill86 great, thanks. It might be a few days but I'll rebase as soon as I can.

**Comment by will-hart** [comment]
OK, finally got around to rebasing today... and it looks like CircleCI is now failing with a bunch of warnings and deprecation messages.

**Comment by jpgill86** [comment]
Hmm, looks like the commits you previously merged from will-hart#1, will-hart#2, and will-hart#3 were discarded. Can you merge them in again?

**Comment by will-hart** [comment]
Oh yeah of course, I must have forgotten to pull the changes locally. My excuse is I'm a bit sleep deprived at the minute as we've just welcomed a new arrive into our family :). I'll sort it out now.

**Comment by jpgill86** [comment]
Congratulations @will-hart, that sounds like happy news!

I'm beginning to suspect this PR is cursed! After I [fixed a bug in the axographio package](https://github.com/will-hart/python-neo/pull/3) that was causing some tests to fail here, we uncovered [a new set of broken tests](https://github.com/NeuralEnsemble/python-neo/pull/550#issuecomment-413375676) that had [nothing to do with this PR](https://github.com/NeuralEnsemble/python-neo/issues/556) and which popped up because [Travis CI changed their default build settings](https://github.com/NeuralEnsemble/python-neo/issues/556#issuecomment-413550114) within a narrow window of time. After about a month, we [fixed the bugs in Neo](https://github.com/NeuralEnsemble/python-neo/pull/563) and finally had those tests working in Travis CI again. You rebased this PR onto the latest commit in master, which was created just one day earlier and which passed its tests, and amazingly the tests are failing here again!

I've started to characterize the new issue here: #568. Once again, the cause appears to be outside of this PR and, once again, it probably has to do with Circle CI changing their default build settings within that one-day window! Hopefully the new issue can be fixed soon, you can rebase _again_, tests will _finally_ pass, and we can merge AxographIO into master, haha. 🤞

**Comment by will-hart** [comment]
I'm not sure how much more of this emotional roller coaster I can take!!! 😄 OK, I'll wait for the go ahead to rebase again.

**Comment by bjoern1001001** [comment]
@will-hart The tests are fixed in master now, if you rebase now they should hopefully pass.

**Comment by jpgill86** [comment]
Tests are broken again. See #572. @will-hart, don't rebase yet.

**Comment by jpgill86** [comment]
OK, tests are passing on master again. @will-hart, can you rebase once more? Quick, before something breaks again! 🤣

**Comment by jpgill86** [comment]
@will-hart @JuliaSprenger @bjoern1001001 Tests are passing! Ready to merge!

**Comment by JuliaSprenger** [comment]
Congratualtions, finallly everything works. Thanks for staying with this PR for so long!

**Comment by samuelgarcia** [comment]
Vous êtes des champions!!

**Pull request merged**
