### PR TITLE
Add 1016 to spikeglx

### PR DESCRIPTION
**Pull request by alejoe91**
Requested via slack

### CODE REVIEW

**Comment by zm711** [comment]
What's the difference between 1015 and 1016 for NP? (ie, would it be better to test against or do your current tests already cover it's broad features?)

**Comment by alejoe91** [comment]
From @jenniferColonell: "it's a short NHP probe with the linear site configuration, 960 sites, 1.0-like gain and referencing."

**Comment by jenniferColonell** [comment]
1016 is really a twin of 1015. It has a different part number because it's sterilized.

**Review by zm711 — APPROVED** [review]
Thanks @jenniferColonell. Sounds good!

**Pull request merged**
