### PR TITLE
Fix BlackrockIO unable to load nsX without nev

### PR DESCRIPTION
**Pull request by bjoern1001001**
This should fix issue #480, @samuelgarcia.
I implemented the missing checks for the availability of nev files and also added a correct error message for cases when no Blackrock files could be found at all.
This works for Blackrock file versions 2.2 and 2.3, but unfortunately it seems that version 2.1 does indeed require a nev file to be loaded because scaling to Volts can only be done with dig_factor which is included in the nev file. I also added an error message for this case.

Apart from that I added a test for this in test_blackrockio that makes sure correct errors are raised in these cases.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@bjoern1001001: thanks for the patch I will have a look.

For the 2.1, case maybe we could force to read without nev file and in that case we would have not units (units='') and a wrning for that. It could be usefull for instance in spike sorting on theses old files where the units is not mandatory. 
What do you think ?

**Comment by bjoern1001001** [comment]
This sounds like a good idea. The 'old' BlackrockIO had a parameter called 'scaling' where you could basically choose this. So if you agree, I would try to implement it in a more general way for all Blackrock file versions.

**Comment by samuelgarcia** [comment]
For the behavior I propose:
  * scaling=None by default
  * for v>=2.2 take the internal scaling and ```assert scaling is None, 'not used ffor version>2.1```
  * for v==2.1:
    * if scaling is None raise an error
    * if scaling=='' or scaling=='realscaling' load data with the

For the keyword instead of **scalling** maybe **ext_units** or **units_scale** or **signal_units** would be more expressive.

**Comment by bjoern1001001** [comment]
In this case, it would not be necessary to even introduce such a parameter, one could just issue a warning as you first suggested.
In certain cases like this there could be advantages (e.g. memory consumption) to being able to keep original scaling and not even convert to float but rather keep the data as int. For this, an explicit scaling keyword would be necessary. The important question now is, if we want to offer the option to acces all data in the original int data type as present in the file. This would require a change in rescale_signal_raw_to_float() and the introduction of a scaling keyword, which could be called something like 'amplitude_scaling' or similar, because 'units' might be misleading because this term appears in many different places with different meanings (e.g. neo.units).

**Comment by samuelgarcia** [comment]
I am back.
Thank for teh code.
Finaly, I am more happy with my first comments : "with 2.1 no nev then no scaling no units".

The actual code is : "with 2.1 no nev then raise error", no ?
I think reading nsx v2.1 than lost there nev v2.1 should be able to be readable.

**Comment by bjoern1001001** [comment]
I agree about version 2.1. This should be possible and thus will not be able to be scaled.
I will check my code again and report back when I'm sure it does this correctly.

For the scaling parameter and thus memory usage, I will create a new issue or PR in the future.

**Comment by bjoern1001001** [comment]
I updated my code so it can now load any nsX file correctly without nev. For version 2.1 it now only shows a warning that raw data will be given instead of a voltage.

**Comment by samuelgarcia** [comment]
OK for me. I merge it.

**Pull request merged**
