### PR TITLE
Tdtraw fixes

### PR DESCRIPTION
**Pull request by cboulay**
See #415

### CODE REVIEW

**Comment by cboulay** [comment]
Don't merge yet. I received another reply from Mark Hanus at TDT and there are a couple more small changes I'd like to make which I will get to tonight.

**Comment by cboulay** [comment]
OK it should be good to merge now.

**Comment by samuelgarcia** [comment]
Oh yeah.
All of this looks good.
Thank you very much.
Have you run test under py2 and py3 with nosetest ?

**Comment by cboulay** [comment]
It passes in py3. I can try with py2 from a different machine tomorrow. By the way, the tech support director from TDT sent me a PDF that has the Tank format description. Is there somewhere I can upload it so it is available for future devs?

**Comment by samuelgarcia** [comment]
There are no special place to put this document.
Maybe you can mention in code where did you have the doc.

I would be happy to have this PDF if can send me directly sam.garcia.die@gmail.com.

Don't forget to add your authorship in tdtrawio.py and doc/source/authors.rst.

**Comment by cboulay** [comment]
Authorship added.

In py2 I get the same error for almost all of the IOs, including TDT:

```
======================================================================
FAIL: test_assert_readed_neo_object_is_compliant (neo.test.iotest.test_tdtio.TestTdtIOIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "neo/test/iotest/common_io_test.py", line 507, in test_assert_readed_neo_object_is_compliant
    assert_neo_object_is_compliant(obj)
  File "neo/test/tools.py", line 169, in assert_neo_object_is_compliant
    assert_neo_object_is_compliant(child)
  File "neo/test/tools.py", line 169, in assert_neo_object_is_compliant
    assert_neo_object_is_compliant(child)
  File "neo/test/tools.py", line 141, in assert_neo_object_is_compliant
    (attrname, classname, type(obattr), attrtype)
AssertionError: ("name in Unit is <type 'numpy.unicode_'> should be <type 'str'>", 'from Unit 0 of ChannelIndex', 'from ChannelIndex 35 of Block', 'from aep_05 with cascade=True and lazy=True')
```

**Comment by samuelgarcia** [comment]
OK.
No problem for the py2 error.
I will fix it in the master. I guess it is in neo.io.BaseFromRaw.
I think we can merge it.

**Pull request merged**
