### PR TITLE
Write Proxyobjects with NixIO

### PR DESCRIPTION
**Pull request by JuliaSprenger**
This PR add enables the NixIO to write ProxyObjects by loading them on request and adds a test for this.

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
@achilleas-k: Could you have a look? I am a bit surprised I only needed to add a Proxyobject case in the comparison of AnalogSignals and not for other dataobject. Maybe I missunderstood your `write_and_compare` function?

**Comment by achilleas-k** [comment]
Indeed, my tests are a messy behemoth.  Thanks, I'll have a look.

**Comment by achilleas-k** [comment]
Found the issue:
https://github.com/NeuralEnsemble/python-neo/blob/b151b253a97a812900e402b3886fa88190d864fd/neo/test/iotest/test_nixio.py#L240-L245

These conditions don't have a default `else` clause so they run through without checking the objects.  Could add an `else` block at the end to fail the test and an `eest.load()` if it matches the Proxy objects:

```diff
diff --git a/neo/test/iotest/test_nixio.py b/neo/test/iotest/test_nixio.py
index b218c5d6..af3452ae 100644
--- a/neo/test/iotest/test_nixio.py
+++ b/neo/test/iotest/test_nixio.py
@@ -223,6 +223,8 @@ class NixIOTest(unittest.TestCase):
     def compare_eests_mtags(self, eestlist, mtaglist):
         self.assertEqual(len(eestlist), len(mtaglist))
         for eest in eestlist:
+            if isinstance(eest, (EventProxy, EpochProxy, SpikeTrainProxy)):
+                eest = eest.load()
             mtag = mtaglist[eest.annotations["nix_name"]]
             if isinstance(eest, Epoch):
                 self.compare_epoch_mtag(eest, mtag)
@@ -230,6 +232,8 @@ class NixIOTest(unittest.TestCase):
                 self.compare_event_mtag(eest, mtag)
             elif isinstance(eest, SpikeTrain):
                 self.compare_spiketrain_mtag(eest, mtag)
+            else:
+                self.fail("Stray object")
 
     def compare_epoch_mtag(self, epoch, mtag):
         self.assertEqual(mtag.type, "neo.epoch")
```

**Comment by JuliaSprenger** [comment]
@achilleas-k: Thanks! I added the suggested changes. Are you happy with the rest of the implementation?

**Comment by achilleas-k** [comment]
Yeah it looks good.  Nice and straightforward.

Maybe add a test for IrregularlySampled signal too?

**Comment by samuelgarcia** [comment]
there is no IrregularlySampledSignalProxy yet.

**Comment by achilleas-k** [comment]
That explains it :)  LGTM then!

**Comment by JuliaSprenger** [comment]
@samuelgarcia: Then we are ready to merge, right?

**Comment by samuelgarcia** [comment]
Do you want me to merge ?

**Comment by JuliaSprenger** [comment]
@samuelgarcia: Yes, you do it.

**Comment by samuelgarcia** [comment]
Oups. This PR was OK with ciclrci but now it trig errors for all new PR.
@JuliaSprenger : any idea how to fix this ?

**Comment by achilleas-k** [comment]
> Oups. This PR was OK with ciclrci but now it trig errors for all new PR.
> @JuliaSprenger : any idea how to fix this ?

I recognise the error.  It looks like the one that Robin reported in #694 and was fixed in #695 but I can't figure out how it returned.  Looking into it.

**Comment by achilleas-k** [comment]
I think I figured it out: The issue is that the fix I made to the NIXIO in #695 isn't mirrored in the NIX RawIO, so the same issue is happening again.  I'll dig deeper and write up a fix.

**Pull request merged**
