### PR TITLE
[NeuralynxRawIO] Test data and fixes for BML style ncs files.

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
Provides some fixes and test data for BML style Neuralynx .ncs files which have fractional sampling frequencies and microsPerSamp. 

Best merged here after PR #890 is merged. 

This will not pass integrations tests until GIN PR #23 is merged into master there.

### CODE REVIEW

**Comment by PeterNSteinmetz** [comment]
Ignoring these line break and indent PEP8 comments as before.

**Comment by PeterNSteinmetz** [comment]
This should pass tests when gin pull request #23 is merged into master there.

**Comment by PeterNSteinmetz** [comment]
Holding off on creating other pull requests until the preceding and this are merged into base master. There has started to be too much divergence.

**Comment by JuliaSprenger** [comment]
Hi @PeterNSteinmetz, sorry for the delay, we are in the process of making a new release, so there's a quite a bit moving currently. I will come back to you when things have settled again.

**Comment by PeterNSteinmetz** [comment]
Closed and incorporated into new PR.

**Pull request closed without merging**
