### PR TITLE
[W.i.p] test_nixio.py

### PR DESCRIPTION
**Pull request by teogale**
End of my internship. Here are the latest modification i made to test_nixio.py not everything is working.
Probably some part or also missed.

### CODE REVIEW

**Comment by achilleas-k** [comment]
Hi.  I had a look at the PR and everything looks good in general.  There's a couple of small issues that  are causing the tests to fail.  Here's a patch (and explanation) that should fix the issues.

One issue that appears in a few places is that the ImageSequence constructor ignores Quantities in the `image_data` attribute and converts that data to a dimensionless array.  Units for the data need to be specified with the `units` attribute.  Some tests were failing because when writing and then reading back an ImageSequence, the units were lost (not read) since the reader part of the NixIO was creating ImageSequence objects with a Quantity.  See the following patch for a fix:
```patch
diff --git a/neo/io/nixio.py b/neo/io/nixio.py
index b166b8fb..b6f749b4 100644
--- a/neo/io/nixio.py
+++ b/neo/io/nixio.py
@@ -465,7 +465,6 @@ class NixIO(BaseIO):
         neo_attrs["nix_name"] = metadata.name  # use the common base name
         unit = nix_da_group[0].unit
         imgseq = np.array([d[:] for d in nix_da_group]).transpose()
-        imgseq = create_quantity(imgseq, unit)
 
         sampling_rate = neo_attrs["sampling_rate"]
         del neo_attrs["sampling_rate"]
@@ -473,7 +472,8 @@ class NixIO(BaseIO):
         del neo_attrs["spatial_scale"]
 
         neo_seq = ImageSequence(image_data=imgseq, sampling_rate=sampling_rate,
-                                spatial_scale=spatial_scale, **neo_attrs)
+                                spatial_scale=spatial_scale, units=unit,
+                                **neo_attrs)
 
         self._neo_map[neo_attrs["nix_name"]] = neo_seq
         # all DAs reference the same sources
diff --git a/neo/test/iotest/test_nixio.py b/neo/test/iotest/test_nixio.py
index 982537fd..bb5f3a1c 100644
--- a/neo/test/iotest/test_nixio.py
+++ b/neo/test/iotest/test_nixio.py
@@ -896,9 +896,10 @@ class NixIOWriteTest(NixIOTest):
         seg = Segment()
         block.segments.append(seg)
 
-        imgseq = ImageSequence(image_data=self.rquant((19, 10, 15), pq.V),
+        imgseq = ImageSequence(image_data=self.rquant((19, 10, 15), 1),
                                sampling_rate=pq.Quantity(10, "Hz"),
-                               spatial_scale=pq.Quantity(10, "micrometer"))
+                               spatial_scale=pq.Quantity(10, "micrometer"),
+                               units=pq.V)
         seg.imagesequences.append(imgseq)
         self.write_and_compare([block])
 
@@ -1125,8 +1126,7 @@ class NixIOWriteTest(NixIOTest):
                 for imgseqdx in range(nimgseq):
                     imseq = ImageSequence(
                         name="{}:imgs{}".format(seg.name, imgseqdx),
-                        image_data=np.random.rand(20, 10, 10)
-                        ,units=pq.mV,
+                        image_data=np.random.rand(20, 10, 10), units=pq.mV,
                         sampling_rate=pq.Hz, spatial_scale=pq.micrometer
                     )
                     print(imseq.units)
```

---

The other issue was that ImageSequence objects weren't being added to the list of objects to check for naming conflicts when the `use_obj_names` flag was set.  The test for this feature was failing.  The following single line patch should suffice:
```patch
diff --git a/neo/io/nixio.py b/neo/io/nixio.py
index b6f749b4..13fa73a6 100644
--- a/neo/io/nixio.py
+++ b/neo/io/nixio.py
@@ -1424,6 +1424,7 @@ class NixIO(BaseIO):
             for seg in blk.segments:
                 signals.extend(seg.analogsignals)
                 signals.extend(seg.irregularlysampledsignals)
+                signals.extend(seg.imagesequences)
                 eests.extend(seg.events)
                 eests.extend(seg.epochs)
                 eests.extend(seg.spiketrains)
```

---

Finally, there's part of a test that retrieves the number of signals (channels) in an AnalogSignal or IrregularlySampledSignal by assuming the signals are 2-dimensional and getting the second dimension from the output of `np.shape()`.  There's a change in this PR that does the same for ImageSequence by getting the third dimension.  This doesn't seem to generalise well for all the tests, so I changed it to just index the result of `np.shape()` with `-1`.

```patch
diff --git a/neo/test/iotest/test_nixio.py b/neo/test/iotest/test_nixio.py
index bb5f3a1c..e4350907 100644
--- a/neo/test/iotest/test_nixio.py
+++ b/neo/test/iotest/test_nixio.py
@@ -194,10 +194,7 @@ class NixIOTest(unittest.TestCase):
             for da in data_arrays:
                 if da.metadata.name == nixname:
                     dalist.append(da)
-            if nixname[:17] == "neo.imagesequence" or nixname[11:15] == "imgs":
-                _, _, nsig = np.shape(sig)
-            else:
-                _, nsig = np.shape(sig)
+                nsig = np.shape(sig)[-1]
             totalsignals += nsig
             self.assertEqual(nsig, len(dalist))
             self.compare_signal_dalist(sig, dalist)
```

**Comment by teogale** [comment]
Hi, thanks for the comment happy to see the modification was globally good  , i pushed the modification but ci/circleci is failling from test_read_all (neo.test.rawiotest.test_nixrawio.TestNixRawIO)

**Comment by achilleas-k** [comment]
The failing test is unrelated, as far as I can tell.

I mentioned it in this PR https://github.com/NeuralEnsemble/python-neo/pull/767#issuecomment-554322399
but I haven't heard back about it so I'm not sure if that's the real cause.

**Comment by JuliaSprenger** [comment]
@achilleas-k: Since #767 is merged now and the tests are succeeding, would you still like to add the proposed changes to the nixio?

**Comment by achilleas-k** [comment]
Done.

**Comment by apdavison** [comment]
replaced by #804

**Pull request closed without merging**
