### PR TITLE
Spikeglx filesize check

### PR DESCRIPTION
**Pull request by Saksham20**
I came across some pair of spikeglx imec output files that have different value of filesize (of the `.bin`) file than that retrieved from the `.meta` file.
While this may be a faulty .meta file, but I think an exception should be thrown while parsing such a file.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Saksham,
I would put an option to control this and by default I would not for ce the checking.
very often we reduce the bin without changing the meta file.
And it is the case for the file on tests.

**Comment by JuliaSprenger** [comment]
@samuelgarcia Is the file reduction only for test files or do you do this also for files that are used in analysis? In the first case I would still think that we should always assume the data and metadata info is compatible, i.e. we should update the test files according to the file reduction.

**Comment by JuliaSprenger** [comment]
@Saksham20 can you rebase on master? The failing tests should be fixed now.

**Comment by samuelgarcia** [comment]
@JuliaSprenger : some people reduce the file itself when it is too long. Sometimes just to try sorting.
Forcing the check of file size will be annoying. And this will lead to lot lot github issue.

**Comment by Saksham20** [comment]
> @JuliaSprenger : some people reduce the file itself when it is too long. Sometimes just to try sorting. Forcing the check of file size will be annoying. And this will lead to lot lot github issue.
> 
> I would prefer a warning rather than a eroor for this.

But if a different file size, then it will construct wrong dimensions of the raw array from the .bin file no?

**Comment by samuelgarcia** [comment]
No because it use the size from the memmap not from the meta.

**Comment by JuliaSprenger** [comment]
@samuelgarcia I changed the error to a warning. Do you think we can merge this?

**Comment by samuelgarcia** [comment]
I still think that forcing this check is a bad thing.
Very often the bin file is manually cut.
We should had this test as an option False by default.
I think using size from the real data (memmap) is better that the one from meta file.

**Comment by JuliaSprenger** [comment]
Hi Sam,
for exactly these reasons there is only a warning when .meta and .bin contain inconsistent information and not an error. If the user works on cut files than this warning would be expected, but for complete sessions it can still detecting flawed recording sessions.

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
