### PR TITLE
Should fix issue 253.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Test are all failing with ```pip install -r requirements.txt --use-mirrors```.
Any ideas ?

**Comment by apdavison** [comment]
`--use-mirrors` has been deprecated for a long time. I think they finally removed it from pip entirely.

Removing the option from the travis.yml file should fix it.

**Comment by samuelgarcia** [comment]
Thanks.

**Comment by samuelgarcia** [comment]
Can I merge ?

**Pull request merged**
