### PR TITLE
Issue270

### PR DESCRIPTION
**Pull request by jgonin**
#270 has been fixed and a corresponding test has also been added. Note that the import bug we had is not fixed but it does not block us and we can continue to move forward. 

Small midifications has also been done in the examples in order to make it run and learn from it.

### CODE REVIEW

**Comment by jgonin** [comment]
(I know I should have done the changes of the examples in an other branch but it was already done and I thought it was not critical. Next time I will stay specifically on the considered issue)

**Comment by apdavison** [comment]
Unfortunately, as you can see from the [Travis CI build](https://travis-ci.org/NeuralEnsemble/python-neo/builds/199206587), the `test/generate_datasets.py` script does not respect the constraint that the number of waveforms be equal to the number of spikes, so there are lots of test failures. Please can you amend `generate_datasets.py` to avoid this?

**Comment by jgonin** [comment]
Ok, thank you for making me notice that. Before the pull request, I ran the
nosetest and got 0 error but 150 skips, I am trying to see why in the same
time.

2017-02-07 14:59 GMT+01:00 Andrew Davison <notifications@github.com>:

**Comment by apdavison** [comment]
Nice work!

**Pull request merged**
