### PR TITLE
Nlx pick channels

### PR DESCRIPTION
**Pull request by sin-mike**
Dear @samuelgarcia , I've added a function to facilitate the selection of channels, which we lack in our lab.

It is on top of the #726 as you suggested.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Why don't you use the new lazy object for channel selection in neo.io ?
https://neo.readthedocs.io/en/latest/io.html#lazy-option-and-proxy-object

Note that could can also load channel in rawio level with index, ids and names:
https://neo.readthedocs.io/en/latest/rawio.html#basic-usage

From what I anderstand, in this patch you hide some channel after parse.
I am not sure how it will be compatible for neo.ioNeuralynxIO.

Am I missing something ?

**Comment by sin-mike** [comment]
> Why don't you use the new lazy object for channel selection in neo.io ?
> https://neo.readthedocs.io/en/latest/io.html#lazy-option-and-proxy-object
> 
> Note that could can also load channel in rawio level with index, ids and names:
> https://neo.readthedocs.io/en/latest/rawio.html#basic-usage
> 
> From what I anderstand, in this patch you hide some channel after parse.
> I am not sure how it will be compatible for neo.ioNeuralynxIO.
> 
> Am I missing something ?

@samuelgarcia my motivation was to be able to keep only the necessary channels for further manipulation. In addition, it keeps the order of the channels, if you want to use the order other than the lexicographical one

**Comment by sin-mike** [comment]
@samuelgarcia 
So, I took a dive into the code and found some inconvenience, that people in my lab won't handle
E.g. the code from `analogsignal.load`
```
raw_signal = self._rawio.get_analogsignal_chunk(block_index=self._block_index,
                    seg_index=self._seg_index, i_start=i_start, i_stop=i_stop,
                    channel_indexes=self._global_channel_indexes[channel_indexes])
```
It uses `channel_indexes` from the global range, rather than actual signal names
How do you think, if I expand this to handle the actual channel names, would it work for you?

**Comment by samuelgarcia** [comment]
I think this patch could be generalized to all rawio with an external function like this:
```python
full_channel_reader = MyRawIO(...)
# by index
some_channel_reader = reduce_channel_on_io(full_channel_reader, channel_indexes=[0,5,12])

# by name if unique
some_channel_reader = reduce_channel_on_io(full_channel_reader,
                                                         channel_names=['CH0', 'CH5'])
# by id if unique
some_channel_reader = reduce_channel_on_io(full_channel_reader, 
                                                 channel_ids=[1, 6, 12])

```
(the name of the function must be better :) )

And also, we could propagate this into neo.io with BaseFromRaw.

What do you think ?

**Comment by samuelgarcia** [comment]
get_analogsignal_chunk already support index/name/ids.

**Comment by sin-mike** [comment]
> ```python
> 
>                                                          channel_
> ```

@samuelgarcia  this is a bit bigger than I thought my patch would be. I need a timeout for a tour to the big code

**Comment by sin-mike** [comment]
@samuelgarcia 
No, it was pretty fast, I understood your idea
I can start fixing with this one:
```
def channel_name_to_index(self, channel_names):
        """
        Transform channel_names to channel_indexes.
        Based on self.header['signal_channels']
        """
        ch = self.header['signal_channels']
        channel_indexes, = np.nonzero(np.in1d(ch['name'], channel_names))
        assert len(channel_indexes) == len(channel_names), 'not match'
        return channel_indexes
```
2 problems:
1. When you select with channel names, the returned order becomes broken, therefore the user must additionally bother about sorting stuff.
2. When you provide list of channel names bigger than the actual list, the API could unsafely return everything it finds (e.g. in strict_slicing=False), rather than asserting.

**Comment by samuelgarcia** [comment]
@sin-mike : can I close ethis ?

**Comment by samuelgarcia** [comment]
I colse this and leave #730 open.

**Pull request closed without merging**
