### PR TITLE
NeuralynxIO: Factor out header handling.

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
This factors parsing the NlxHeader into parts and provides an option to construct without testing for time and date.

### CODE REVIEW

**Comment by PeterNSteinmetz** [comment]
This is failing because the test data are not in ephy_testing_data yet. For that I am waiting on clarification of how to check the files in. See the google groups thread "New workflow with datalad?"

**Comment by zm711** [comment]
Regarding your google group message about incorporating some of your local code. Could you describe a bit more what it is doing? I think making things more robust/flexible would be great, but it also needs to fit within the Neo framework. So you can either open an issue to discuss what you're proposing if you have a hunch that your code might be bigger changes to neuralynx. Or you could open a draft PR and see what happens in the test suite with the rest of the code if you incorporate some of your code.

**Comment by PeterNSteinmetz** [comment]
I added pull request #116 for ephy_testing_data for the dataset which will allow this to pass checks.

**Comment by zm711** [comment]
@PeterNSteinmetz , @samuelgarcia is going to look over everything very soon for your recent PRs so you'll have feedback on everything asap.

**Comment by samuelgarcia** [comment]
Hi @PeterNSteinmetz.
I remove the new tests for now and I will merge this into main.
So I can start also a PR on top of it.
I let you open a new PR when files are ready.

**Pull request merged**
