### PR TITLE
Global fix of PEP-8 issues

### PR DESCRIPTION
**Pull request by apdavison**
This will probably cause some conflicts with pull requests that are in progress, but we have to bite the bullet at some point.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
red alert. This is massive attack!

This is certainly the wiser approach.

I could make cardiac arrest if the present PR would be merge before WIP #468 that concern all IOs...

**Comment by apdavison** [comment]
ok, I'll rebase this PR after #468 is merged. I see that the CircleCI tests are failing for that PR at the moment.

**Comment by apdavison** [comment]
ok, rebased on top of master after merging #468

**Comment by samuelgarcia** [comment]
I guess this is the next PR to merge.
Ok for anybody ?

Really strange that this PR make TDT test fail again. And only on 2.7.
Maybe we can clear the cache and re run circle.

**Comment by apdavison** [comment]
I've already cleared the cache and re-run. It looks as though the test failures are not due to this PR - the tests failed on master after merging PR #468 ("Clean cascade and lazy") - https://circleci.com/gh/NeuralEnsemble/python-neo/tree/master

**Comment by samuelgarcia** [comment]
I propose to merge this now.
The test is clearly unrelated to the PR.
So all of us will be able to rebase again this pep8 clean.
OK ?

**Comment by apdavison** [comment]
go for it (my PR, so you should merge!)

**Pull request merged**
