### PR TITLE
Synchronize version of doc/source/install.rst neo with the one in neo.version

### LINKED ISSUE #449: Add a script to keep version numbers in sync
The version number appears in multiple places: in `neo/version.py`, `setup.py`, `doc/conf.py` and `doc/install.rst`

To simplify making releases, we should make it easier to update all these files at the same time, e.g. with a script.

### PR DESCRIPTION
**Pull request by samuelgarcia**
To fix #449

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
I tested this and it works for me for the installation as well as for the generation of the documentation. Are there any more changes you want to add here?

**Comment by samuelgarcia** [comment]
No change planed.
I think it is OK.

**Comment by JuliaSprenger** [comment]
Could you fix the pep8speaks issues?

**Comment by samuelgarcia** [comment]
Yep.
I can. But theses pep8 come from the autogenerated conf.py of sphinx !!!
This is not me, I swear.

**Pull request merged**
