### PR TITLE
simple fix for spike2io

### PR DESCRIPTION
**Pull request by samuelgarcia**
#948
@eduardacenteno : could you test this ?

### CODE REVIEW

**Comment by eduardacenteno** [comment]
> 
> 
> #948
> @eduardacenteno : could you test this ?

hey @samuelgarcia , I tested it in my computer, adding these lines to my spike2rawio.py file indeed solved the issue :)

**Comment by samuelgarcia** [comment]
Ready to reveiw and merge if OK

**Comment by samuelgarcia** [comment]
Ready to review (and merge maybe)

**Comment by samuelgarcia** [comment]
@apdavison @JuliaSprenger : can we merge this ?

**Comment by JuliaSprenger** [comment]
@eduardacenteno I assume this fixes your issue. Please comment if this is not the case.

**Pull request merged**
