### PR TITLE
[neuralynx] reintroduce spiketime and recording trace tests

### LINKED ISSUE #907: [NeuralynxIO] Tests of keep_original_spike_times failing
The tests in test_neuralyxio.test_keep_original_spike_times are failing for the test data in Cheetah_v5.5.1 on the .nse files. 

It is not clear to me why these have been hidden previously, though that might have to do with the code which only ran the first two blocks of tests.

### PR DESCRIPTION
**Pull request by JuliaSprenger**
fixes #907

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
@PeterNSteinmetz @samuelgarcia What do you think?

**Comment by PeterNSteinmetz** [comment]
The question will be -- do these pass? My recollection is that there is some difference in the format of the test plain text data files in terms of column structure between the difference Neuralynx versions being tested. I believe these files were generated with several different programs.

**Comment by JuliaSprenger** [comment]
The tests pass, so it seems the inconsistency was fixed. I only had to adjust the timestamp column id for nse files.

**Comment by PeterNSteinmetz** [comment]
Then seems good by me.

**Comment by samuelgarcia** [comment]
Hi Julia and Peter.
To be honest, I don't remember about this test removal, so it is OK for me.
Tell me if i can merge.

**Comment by JuliaSprenger** [comment]
Ready to merge :)

**Pull request merged**
