### PR TITLE
SpikeGLX: add Ultra and NP-Opto types

### LINKED ISSUE #1451: [SpikeGLX] Support imDatPrb_type 1100
Stemming from https://github.com/NeurodataWithoutBorders/nwb-guide/issues/713

A user with a SpikeGLX `.meta` file contains the field `imDatPrb_type=1100`, which has been unseen before and triggers an error at line https://github.com/NeuralEnsemble/python-neo/blob/883b29a28575b23f04189aca49a4a562b606a685/neo/rawio/spikeglxrawio.py#L470

You can replicate this easily by using existing SpikeGLX test data (including Noise4Sam) and replacing that line (which is probe type `0` for the classic NP v1 probes)

To my possibly naive eyes the rest of the meta files (which can be found attached to the original issue as `.txt` files) appear consistent with other v1 `.meta` files (384 channels on one shank + SY)

### PR DESCRIPTION
**Pull request by alejoe91**
Fixes #1451 

also adding Ultra-beta variant (1121) ant NP-Opto (1300). All these models are based on NP1.0 technology

@CodyCBakerPhD

### CODE REVIEW

**Comment by zm711** [comment]
This looks fine to me. Are there any test files that could help us double check that adding just there works (other than seeing that it seemed to work in the issue)?

**Comment by alejoe91** [comment]
I don't have any, but it should be fine :)

**Comment by alejoe91** [comment]
Test data uploaded here: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/129

@zm711 could you check (and merge) the GIN PR?

**Comment by zm711** [comment]
Merged :) and just reran tests.

**Review by zm711 — APPROVED** [review]
Test for NP-ultra added and passed looks good to me.

**Pull request merged**
