### PR TITLE
[BlackrockIO] Refactor __transform_channels

### PR DESCRIPTION
**Pull request by rohanshah**
### Motivation
The `__transform_channels` function only returns continuous data channels or spike data channels but not both, even when both `nsx_to_load='all'` and `channels='all'`. This shouldn't be the case.

This change also cleans up the logic in the function by grouping conditions based on what they'll return and does some minor edge case handling.

Closes https://github.com/NeuralEnsemble/python-neo/issues/333

### Notes
It might be easier to just compare the entire new function with the old one than look at the diff since git has it split it up weirdly.

### Testing
- Imported and validated data from multiple Blackrock data sets.

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
I opened a PR to fix the merge issues in this PR (https://github.com/Blackfynn/python-neo/pull/7). Can you have a look at it? If you have a minimal dataset where the spiketrain channels are not a subset of the analogsignal channels, could you provide this to / and implement a unittest covering this?

**Comment by rohanshah** [comment]
@JuliaSprenger thanks! I've been trying to fix the merge conflict myself today but I've been running into a lot of errors. I'll check out your branch and see if it works with my datasets, and let you know the result!

**Comment by rohanshah** [comment]
@JuliaSprenger I looked through your merge and I'm a little hesitant to approve it as there are some logical inconsistencies between the new changes since my PR and my my changes. For instance, `master` branch now returns a subset of `channel_ids` if `all_channels` is a superset of `channels` whereas my changes did not have that at the time, and your merge removes this update.

I have committed my own merge of the master branch here with the logic as it was at the time of my pull request.

However, I am getting errors trying to validate my dataset with my updated PR. I think there have been too many changes at this point to safely recover the original PR I made. I'll play around the `master` branch and see if I can re-write my PR in a way that is consistent with all the updates.

Thank you for looking at this though! I hope to have a new PR out soon. Would I be able to tag you for a review at that time?

**Comment by JuliaSprenger** [comment]
@rohanshah Sounds like a good plan. Thanks for putting your effort into the BlackrockIO! I would be happy to review the next PR.

**Comment by samuelgarcia** [comment]
@rohanshah Do you means that we can safetly close this PR without merging ?

@rohanshah I hope to merge more or less soon this PR #355. This is complete rewrite of many IOs included BlackrockIO. Before doing any effort in the actual BlackrockIO could you have a look in the next neo.rawio.BlackrockRawIO to avoid duplicated work.

Best

Samuel

**Comment by rohanshah** [comment]
@samuelgarcia yes, I will close this PR now. I will also take a look at the new reader and make sure that I'm not conflicting with any of the changes you've made. Cheers!

**Pull request closed without merging**
