### PR TITLE
Add an alias for `duplicate_with_new_data`, for backwards compatibility.

### PR DESCRIPTION
**Pull request by apdavison**
See #621 

I propose to make a release with version 0.7.1 as soon as this is merged, so that we can reduce the impact of updating Neo on downstream projects. What do you think @samuelgarcia ?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I agree with this and making a release.
But we have already some commit since the the release.
Do you propose a release with only this in a branch or with the current master ?

In any case I am OK.

**Comment by apdavison** [comment]
As far as I can see, all the commits since 0.7.0 are minor fixes, so I plan to release from master.

**Comment by samuelgarcia** [comment]
OK.

**Comment by jpgill86** [comment]
Since `duplicate_with_new_array` is deprecated, should an issue be created to eventually remove it, tagged with milestone 0.8.0 (or 0.9.0)?

**Comment by apdavison** [comment]
@jpgill86 Go for it! (I suggest 0.9.0 to give people enough time to adapt, as 0.8.0 will be out quite soon).

**Comment by jpgill86** [comment]
Done, though I don't have the ability to tag the new issue with a milestone.

**Pull request merged**
